### ISSUE TITLE
Are there plans to enable relationships to be accessible via REST?

### ISSUE THREAD

**Issue by thomasgauvin** [Azure/data-api-builder#1082]
The current relationships documentation states that the relationships functionality can only be used by GraphQL requests https://github.com/Azure/data-api-builder/blob/main/docs/relationships.md. Are there any plans to allow REST access to leverage the relationships, and get items with their relationships if desired?

**Comment by daneel3001** [comment]
@Aniruddh25 I am trying Data API Builder. If REST is a secondary objective for Data API Builder, does that mean that one may have to run two instances of DAB. One optimised for REST consumption and one for GraphQL ? 
And am I correct that this design decision will require creation of many joining entities and that it's not possible to have sub-resources either ?
