### ISSUE TITLE
REST: Add support for url template with implicit primary key field names

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1085]
Today, we need to provide the primary key name explicitly when performing a point operation through REST APIs.
e.g. `/data-api/api/Books/id/5`.
We need to add support for being able to perform the same point operation without specifying the primary key in the route .i.e. `/data-api/api/Books/5` should mean operation on the id=5

**Comment by seantleonard** [comment]
Did you envision that we also support simplified url access for composite primary keys? 
```https
GET /api/entity/5/other-value
GET /api/entity/other-value/5
```
How would we define the order in which PK values are resolved?

**Comment by JerryNixon** [comment]
Closing until customer demand,
