### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#1099]
Here's my proposal for the roadmap for next months, regarding the features we want to add and support.

**(APR 2023) 0.7** 
- Add support to OpenAPI for exposed REST endpoints
- Add support to M2M (many-to-many) mutations (explicit transactions) [GraphQL]

**(JUNE 2023) 0.9**
- Add support for defining a limit in how nested queries can be
- Add support for Engine Policies (prevent execution of database queries if engine policies are not respected)
- Allow more complex policies (allow usage of JSONPath to access claims data)

**(AUG 2023) 0.11**
- Add support for caching response (integration with FusionCache and Redis)

Of course, we'll adjust these based on the feedback we'll receive,

**Comment by hannesne** [comment]
I spent a bit of time looking for OData support - can I ask for a short note somewhere in the docs (readme?) about where it's at and the plan for it?

**Comment by yorek** [comment]
@hannesne we'll evaluate the support for OData after we are done with the planned features, so after August 2023.

**Comment by yorek** [comment]
Closing this issue as the toadmap discussion moved here https://github.com/Azure/data-api-builder/discussions/1377 as better for keeping the discussion going.
