### ISSUE TITLE
Automate publishing release artifacts to PROD storage account

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1101]
Now that the manifest file/other release artifacts are being hosted in a PROD storage account (issue #886), we need to automate publishing it there as part of the release.

**Comment by abhishekkumams** [comment]
The task that can be used to publish to Azure storage is [FileCopy@4](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-file-copy-v4?view=azure-pipelines)

**Comment by abhishekkumams** [comment]
We will be using github link directly from Release page to download the assets. It will help maintaining the files as there will be less duplication.
