### ISSUE TITLE
Configuration - Specify which JWT claims pass through to MSSQL Session Context

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#1113]
As per discussion here: #1094, it would be good to have a way to define which element of the received JWT token are passed into the SESSION_CONTEXT. For example:

```
"context":{
  "userId":[$.user_id,$.objectid],
 "roles":"[$.userroles,$.roles]
}
```

**Comment by Aniruddh25** [comment]
No feedback provided, yet - moving to May2023 until we know what the requirements are

**Comment by JerryNixon** [comment]
Related #1096

**Comment by JerryNixon** [comment]
Related #1094
