### ISSUE TITLE
Enhanced GraphQL Global Enable Flag Processing

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#1168]
Per https://github.com/Azure/data-api-builder/pull/1107#discussion_r1089474997

The GraphQL endpoint is properly restricted when global GraphQL is disabled. However, we still create a schema behind the scenes. This would be enhanced if we could identify configuration to not process a GraphQL schema if none is required.

**Comment by abhishekkumams** [comment]
Tested it out, This has already been addressed in the PR: https://github.com/Azure/data-api-builder/pull/1255. 
Graphql Schema is not generated when GraphQL endpoints are disabled.
