### ISSUE TITLE
REST: Strategize usage of Exceptions vs. Error codes for request validation

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#121]
While implementing PrimaryKeyValidation PR #113, I utilized exceptions to bubble up to the REST controller to appropriately return 400 vs. 500 errors. However, while working on this, I came across lots of debate (opinion) on whether to utilize exceptions here.

Invalid requests could be considered 'extraordinary' circumstances, and we can throw exceptions like we are now.

However, we could reasonably expect clients to send invalid requests to our API. In that case, a design where we mark validation failure on some sort of Response object and cease continuing the validation might be an option. Can we as a team pick one way vs. another? In Microsoft Docs, there are remarks indicating that Exceptions have a performance impact we need to consider and that exceptions should not be used for user input validation. [Microsoft Docs](https://docs.microsoft.com/dotnet/api/system.exception?view=net-6.0#performance-considerations): "_Do not throw an exception if user input is invalid, because you can expect users to occasionally enter invalid data._" Should a user composed request be considered "user input?"

**Comment by bbrandt** [comment]
My preference when building these types of API's have been a bit towards user friendliness rather than raw performance, so I would recommend aggregating all validation failures into a response rather than having the user play exception whack-a-mole, fixing one exception, then the next, then the next...

**Comment by seantleonard** [comment]
https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/exceptions-and-performance

**Comment by seantleonard** [comment]
While a good discussion, switching from exception usage to error codes would be a drastic refactor of the dab engine. I don't expect this to be changed unless we identify a concrete performance issue after all other perf enhancements that may come.
