### ISSUE TITLE
[Docs]: App Service / ACA deployment

### ISSUE THREAD

**Issue by ErikEJ** [Azure/data-api-builder#1339]
### What happened?

Missing docs on App Service container deployment.

Also, is ACA supported? - if so, a sample would be helpful

### Version

0.5.34

### What database are you using?

Azure SQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sajeetharan** [comment]
@ErikEJ Thanks for the feedback, Yes you should be able to deploy to Azure App Service as a container. Did you face any issue? We will look into adding a sample on docs.

**Comment by ErikEJ** [comment]
I have not tried, but just noticed that docs were currently not available for that screnario.

As a container noob it would be helpful (and possibly increase adoption)

**Comment by MassimoC** [comment]
It works without any problems.
Just pass the config file via args

**Comment by yorek** [comment]
@MassimoC that is pretty cool! Would be great if you can write a short doc with the steps on how to make it work (for example is a private registry needed?) so that we can add it to the docs.

**Comment by MassimoC** [comment]
Hi @yorek I have docs and working example (with cli and bicep) ready, if you do not mind I will do a PR after this event https://techorama.be/speakers/session/build-a-serverless-costeffective-warp-speed-timetomarket-api-with-dab-and-azure-container-apps/

deal?

**Comment by yorek** [comment]
Absolutely! Looking forward to it!
