### ISSUE TITLE
[Bug]: Errors are not exposed

### ISSUE THREAD

**Issue by ErikEJ** [Azure/data-api-builder#1341]
### What happened?

I have enabled development host mode, but see no errors when 500 errors happen

### Version

0.5.34

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
"runtime": {
    "rest": {
      "enabled": true,
      "path": "/api"
    },
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
    "host": {
      "mode": "development",
      "cors": {
        "origins": [],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      }
    }
  },
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ErikEJ** [comment]
>>  From docs: In either configuration modes, detailed errors are sent to the console output to help with troubleshooting.

I did not see that until I raised the LogLevel via CLI option

**Comment by abhishekkumams** [comment]
@ErikEJ, Thanks for raising the issue. Can you also provide us with the screenshot of the logs you see with `hostmode` as `development` and without using `LogLevel` options.

**Comment by ErikEJ** [comment]
@abhishekkumams I was wrong, I see all output without the LogLevel switch (in the console output)
