### ISSUE TITLE
Add support for providing environment var/values in a `.env` file read by `dotenv.net`

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1374]
### Discussed in https://github.com/Azure/data-api-builder/discussions/1361

<div type='discussions-op-text'>

<sup>Originally posted by **glaucia86** March 25, 2023</sup>

> Hi! 
> 
> I would like to propose that we can make use of the .env file in the `dab.config.json` file.
> As it already happens with the files generated by the SWA CLI: `staticwebapp.database.config.json` (example: **[HERE](https://github.com/Azure-Samples/dab-swa-library-demo/blob/main/swa-db-connections/staticwebapp.database.config.json#L8)**)
> 
> Because the connection string is very exposed, where it has extremely sensitive data such as: login, password and database name.
> 

</div>

This issue is to add support for `.env` so that I can just put my sensitive data into the .env, if I don't need the complexity of having multiple configuration files. 

This is separate from the current `@env()` feature where we need to set environment variables on the system.

**Comment by yorek** [comment]
Two libraries for this option:
- https://github.com/tonerdo/dotnet-env
- https://github.com/bolorundurowb/dotenv.net

**Comment by yorek** [comment]
Looking forward to this! :)
