### ISSUE TITLE
MsSql/PgSql:  Mutations should be done in the same transaction as other mutations in the same request

### ISSUE THREAD

**Issue by JelteF** [Azure/data-api-builder#138]
Multiple mutations should be part of the same transaction. That way they can be rolled back in an atomic way. It also ensures that no unexpected data is returned in the result of a mutation in case of concurrent updates.

**Comment by Aniruddh25** [comment]
@severussundar, what does graphql specs say? With the given observations, should this be fixed or is it the expected behavior?

**Comment by severussundar** [comment]
AFAICT, the GraphQL specs are not explicit about whether the various mutations should be executed within the same transaction.

When the multiple mutation requests are unrelated to each other, it should be okay to not execute them in a single transaction. There maybe some use-cases where rolling back all the effects might be appropriate. 

It appears more of our call on what direction to take.

@yorek @JerryNixon @sajeetharan Please kindly share your thoughts

**Comment by seantleonard** [comment]
Closing this as primary discussion and tracking will proceed with #1780.
