### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by michaelstaib** [Azure/data-api-builder#1382]
While browsing the code I stumbled on the following:
https://github.com/Azure/data-api-builder/blob/5150fad74a9e9e2766a70e1974e4b2109b27d915/src/Service/Services/ResolverMiddleware.cs#L100

This middleware registered as a middleware for all fields.

With version 12 we have introduced pure resolvers which will improve execution performance by multiple times as not each field will be handled as its own resolver task for which we need to rent a context and other things. Instead pure fields ... or simple data fields can be folded into their parent.

This class essentially would be split up into two classes, one that handles the fetching of data and the other one that handles the unpacking of data.

Further we would not use the generic middleware but instead use a type interceptor to give each fields a specific middleware. This also would remove further cases from the class and benefit execution perf and memory allocations during execution.

When we introduced these changes to the introspection in Version 12 we saw the same instance go from 19983 requests per second to 33702 request per second on the same hardware.

Do you guys want to have a go at it with me?

**Comment by Aniruddh25** [comment]
Sure, thanks for bringing this up! If you'd like, feel free to take a stab at it as well :)

**Comment by michaelstaib** [comment]
OK ... got it working ... I opened #1392 as a draft PR and will ping you once I am done.

**Comment by Aniruddh25** [comment]
Im glad you got it working! We are checking how we can solve the feeds issue. FYI @mbhaskar
