### ISSUE TITLE
[Bug]: dockerfile missing

### ISSUE THREAD

**Issue by manasvin** [Azure/data-api-builder#1399]
### What happened?

Please include the Dockerfile of the referenced container image mcr.microsoft.com/azure-databases/data-api-builder:latest so I can review its composition, in this repo.

### Version

NA

### What database are you using?

Azure SQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniruddh25** [comment]
hi @manasvin, the Dockerfile we use to generate the referenced container image is here: https://github.com/Azure/data-api-builder/blob/main/Dockerfile 

You can also use the docker compose files from here [https://github.com/Azure/data-api-builder/tree/main/docker](https://github.com/Azure/data-api-builder/tree/main/docker) to easily spin up the docker image. Make sure to provide the correct configuration file path.

Further instructions on how to run using a container are: https://github.com/Azure/data-api-builder/blob/main/docs/running-using-a-container.md

Hope this helps! 

Closing this issue for now, please reopen if you have any further questions. Thank you for your interest!
