### ISSUE TITLE
[Bug]: Wrong NextLink if using with Azure Static Web Apps

### ISSUE THREAD

**Issue by sebader** [Azure/data-api-builder#1420]
### What happened?

Not sure if this is the right place to address this but...:

When using DAB with Azure Static Web Apps' `/data-api/` the `nextLink` is not usable as it does not get rewritten to reflect the frontend url:

![image](https://user-images.githubusercontent.com/11445087/230365252-1e624439-9818-4fcb-bf6c-e1810570e8ee.png)

![image](https://user-images.githubusercontent.com/11445087/230365295-8ea51bb6-3549-4d5e-adf6-7a6a7ebc0627.png)

### Version

Microsoft.DataApiBuilder 0.6.13+32fc03f4fe439d02aef454f10cc58e50d0d29f79

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Thank you for raising this issue, @sebader. We are looking into this now.
