### ISSUE TITLE
AuthorizationCheckFailed on query with filter after upgrade to 0.6.13

### ISSUE THREAD

**Issue by ksdaniel** [Azure/data-api-builder#1431]
### What happened?

After upgrading to 0.6.13, we get an error for requests that have a filter: 

**Request is:** 

query {
	userActions(filter: { id: {eq: "81249cf4-bcaa-48b0-908d-9eab5cadb4d2"}}){
		items{
			id
		}
	}
}

**Error is:** 

{
	"errors": [
		{
			"message": "Access forbidden to a field referenced in the filter.",
			"extensions": {
				"code": "AuthorizationCheckFailed"
			}
		}
	]
}

**Configuration is:** 

 "UserAction": {
      "graphql": true,
      "source": "actions",
      "permissions": [
        {
          "role": "anonymous",
          "actions": ["*"]
        }
      ]
    }

### Version

0.6.13

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
bool columnAccessPermitted = queryStructure.AuthorizationResolver.AreColumnsAllowedForOperation(
                            entityName: targetEntity,
                            roleName: GetHttpContextFromMiddlewareContext(ctx).Request.Headers[CLIENT_ROLE_HEADER],
                            operation: Config.Operation.Read,
                            columns: new[] { name });

returns false.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dgcaron** [comment]
this is related to #1434 which looks like a duplicate by me, my apologies
