### ISSUE TITLE
[Bug]: Either the parameter query or the parameter id has to be set

### ISSUE THREAD

**Issue by marcelmedina** [Azure/data-api-builder#1474]
### What happened?

This issue is happening all the times I `dab start` my apis.

As soon as I launch the browser `https://localhost:5001/graphql/` I get the following error:

`{"errors":[{"message":"Either the parameter query or the parameter id has to be set.","extensions":{"code":"HC0013"}}]}`

I am running the latest dab version:  `Microsoft.DataApiBuilder 0.6.14+b21a924c4a9220e9cdef36032786b531c6394251`

On the API side, when the error occurs it shows:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/graphql/ - - - 400 - application/json;+charset=utf-8 0.7048ms
fail: Azure.DataApiBuilder.Service.Startup[0]
      HC0013
fail: Azure.DataApiBuilder.Service.Startup[0]
      Either the parameter query or the parameter id has to be set.
```

### Version

Microsoft.DataApiBuilder 0.6.14+b21a924c4a9220e9cdef36032786b531c6394251

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
In your configuration file, do you have host mode set to `Production`?
```json
"host": {
      "mode": "Production"
}
```
That mode would result in the behavior you are seeing. The Banana Cake Pop GraphQL IDE is disabled in production mode, so your browser loading `https://localhost:5001/graphql/` is a essentially sending a GET request to the GraphQL endpoint without any GraphQL request payload.

Setting host-mode to development will get you the Banana Cake Pop UI. Discussion on a more informative user experience is occurring in this issue: https://github.com/Azure/data-api-builder/issues/1124

**Comment by marcelmedina** [comment]
Indeed @seantleonard ! Thanks for the heads up, as soon as I changed to "development", the /graphql path loaded.
