### ISSUE TITLE
[Bug]: Insufficient permissions error when accessing table with appropriate role

### ISSUE THREAD

**Issue by ChrMaass** [Azure/data-api-builder#1483]
### What happened?

I'm currently using the database feature of StaticWebApps, which is built on DataApiBuilder. My setup is such that a role (let's call it 'RoleA') has permissions to perform all actions on a specific entity (let's call it 'EntityA').

My configuration is as follows:

```
{
  "$schema": "https://dataapibuilder.azureedge.net/schemas/latest/dab.draft.schema.json",
  "data-source": {
    "database-type": "cosmosdb_nosql",
    "options": {
      "database": "MyDatabase",
      "schema": "staticwebapp.database.schema.gql"
    },
    "connection-string": "@env('DATABASE_CONNECTION_STRING')"
  },
  "runtime": {
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
    "host": {
      "mode": "production",
      "cors": {
        "origins": ["http://127.0.0.1:5500"],
        "allow-credentials": true
      },
      "authentication": {
        "provider": "StaticWebApps"
      }
    }
  },
  "entities": {
    "EntityA": {
      "source": "SourceA",
      "graphql": {
        "type": {
          "singular": "EntityA",
          "plural": "EntityAs"
        }
      },
      "permissions": [
        { "actions": ["*"], "role": "RoleA" },
        { "actions": ["create"], "role": "anonymous" }
      ]
    }
  }
}
```
When I fetch my authentication data from the .auth/me endpoint, I get the following response:

```
{
  "clientPrincipal": {
    "identityProvider": "aad",
    "userId": "UserID",
    "userDetails": "user@example.com",
    "userRoles": [
      "RoleA",
      "anonymous",
      "authenticated"
    ]
  }
}
```
However, despite being authenticated as a user with 'RoleA', I receive an error stating that I lack the necessary permissions to read from the 'EntityA' table. Interestingly, if I set the permissions for the 'anonymous' role to "*", everything works fine.

This behavior seems unexpected, as I should be able to access 'EntityA' with 'RoleA' permissions. I believe this might be a bug and would appreciate any guidance or assistance in resolving this issue.

### Version

0.6.14+b21a924c4a9220e9cdef36032786b531c6394251

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
{
    "errors": [
        {
            "message": "The current user is not authorized to access this resource.",
            "locations": [
                {
                    "line": 3,
                    "column": 25
                }
            ],
            "path": [
                "entityAs"
            ],
            "extensions": {
                "code": "AUTH_NOT_AUTHORIZED"
            }
        }
    ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Hi @ChrMaass, you'll need to make sure you are including the `X-MS-API-ROLE` header with your request which designates the role in which the request should be evaluated. Data Api builder evaluates the request [in the context of a single role](https://learn.microsoft.com/en-us/azure/data-api-builder/authorization). So in your case, include the header:
`X-MS-API-ROLE` with value `RoleA`

**Comment by ChrMaass** [comment]
In fact, you are right and I seem to have misunderstood. As I understood the documentation, this header entry (according to my assumption by the cookie) is automatically set by a kind of proxy in the static web app, virtually for all existing groups. I had not understood that you still have to pass this manually. 

Now it works anyway, thank you. The ticket can be closed so far, although I would still make the suggestion to sharpen the documentation in this regard.

**Comment by seantleonard** [comment]
Yes, we're currently writing up more documentation, @ChrMaass.

I do want to add one thing about the provided GraphQL file for CosmosDB [schema.gql]. (For which we are also adding more/filling the documentation gap): 
The GraphQL engine under the hood expects a GraphQL schema directive (`@authorize`) to be used with your object type definitions to enforce "read" permissions.

For example:

```graphql
type Book @model(name:"Book"){
  id: ID
  title: String @authorize(roles:["role1","authenticated"])
  Authors: [Author]
}
```

- The use of `@authorize(roles:["role1","authenticated"])` means that only the roles "role1" and "authenticated" can read the title field. This fulfills the permissions configuration denoting "included" and "excluded" fields.
  - If a requestor is already authenticated, they will by default be a member of the system role 'authenticated', no `x-ms-api-role` is required.
- The use of the directive `@model(name:"Book")` is used to correlate this GraphQL object type with the entity name in the runtime config.

Another example:

```graphql
type Book @model(name:"Book") @authorize(roles:["role1","authenticated"]) {
  id: ID
  title: String
  Authors: [Author]
}
```

- Using the `@authorize` directive in the top level type definition will restrict reading this type and its fields to the roles specified in the directive.

**Comment by Aniruddh25** [comment]
Just to clarify expectations - the use of `@authorize` at the field level for CosmosDb_NoSql will be supported in the upcoming release since this PR is checked in #1468 

the use of `@authorize` at the entity level for Cosmosdb_noSql is supported even with the current latest release.

For other databases, field/entity level authZ is generally supported except for the known issues mentioned here: https://learn.microsoft.com/en-us/azure/data-api-builder/known-issues
