### ISSUE TITLE
[Bug]: Undefined Types shown in Example Schema for request body in Swagger

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1508]
### What happened?

Example schema shown in the request body is very useful to know the parameters and it’s types, but for this particular case I see it's not useful and confusing for some composite dataTypes such as datetime.
I am not sure if I should enter a string or some other type.
![image](https://github.com/Azure/data-api-builder/assets/102276754/a9125014-cf86-46ef-8fc8-6d12ab63ef1e)

This is the underlying entity in the database:
```
CREATE TABLE type_table(
    id int IDENTITY(5001, 1) PRIMARY KEY,
    byte_types tinyint,
    short_types smallint,
    int_types int,
    long_types bigint,
    string_types varchar(max),
    single_types real,
    float_types float,
    decimal_types decimal(38, 19),
    boolean_types bit,
    date_types date,
    datetime_types datetime,
    datetime2_types datetime2,
    datetimeoffset_types datetimeoffset,
    smalldatetime_types smalldatetime,
    bytearray_types varbinary(max),
    guid_types uniqueidentifier DEFAULT newid()
);
```

### Version

0.7.5

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
In progress with fix in working branch. need to add tests. Was missing conversion for DateTime and DateTimeOffset -> Json String.

**Comment by seantleonard** [comment]
Branch ready, just waiting on merging Aaron's config change pr.
