### ISSUE TITLE
[Bug]: Error 400 when something is wrong with the connection string

### ISSUE THREAD

**Issue by alexandruilea** [Azure/data-api-builder#1521]
### What happened?

My connection string happened to have a random generated password that contains a semicolon (;) and the static web app would return an error 400 but no other data that could help with the problem. I've solved the issue by adding single quotes on the password field at the **Link your database** step but I think this can be addressed with code so that the single quotes are added by the code itself.

### Version

v0.5.34

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniruddh25** [comment]
hi @alexandruilea, 

thanks for reporting the issue. @thomasgauvin, is this something that can be fixed on the SWA portal side?

**Comment by alexandruilea** [comment]
An error message that would suggest the error better would be
highly appreciated as error 400 in this case is pretty useless. Returning
error 500 would already be an improvement over 400 as I was looking at what
could be wrong with my request while the error came from the configuration
of the backend.

**Comment by thomasgauvin** [comment]
@Aniruddh25, thanks for tagging, I'll coordinate with Portal to get this fixed to escape characters in the connection string
