### ISSUE TITLE
[Bug]: Export command fails to export the graphql schema

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1542]
### What happened?

Even when the engine is started, `dab export` fails to export the graphql schema file.

# How to reproduce?
1. Use the `dab-config.Mssql.json` file update the connection string accordingly.
2. run the command 
```
dab export --graphql -o ./schema --config dab-config.Mssql.json
```

3. Error message is not helpful, it just mentions it failed to export schema file.

### Version

running from main

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
@abhishekkumams  is this still an issue? thought was fixed at some point. if fixed, please associate PR workitem and close.

**Comment by Greven145** [comment]
I was having the same issue and discovered you need to run the export command while the service is running. I was testing this locally and kept getting the above error because I could either execute the command or run `dab start`. Running `dab start`, then opening another terminal and running the export command worked just fine.

**Comment by seantleonard** [comment]
@Greven145 can you share the command you used to attempt to get the schema exported? 

I was able to get a schema exported without manually starting a separate instance of dab running. (dab export launches its own instance of dab to get the schema, you shouldn't be required to do so separately).

```sh
dab export --graphql -o "C:\dabtest\schema_drop" --config "C:\dabtest\dab-config.json"
```

Note:
- The referenced config must be valid (valid connection string, etc.)
- You must also include `--graphql`. I observed that export fails if that is not provided.

**Comment by seantleonard** [comment]
Dab engine is expected to be started temporarily to run GraphQL schema generation to provide a file to dab CLI `export`. Unless this isn't functioning in a specific circumstance, I tested this and it working as designed.
