### ISSUE TITLE
[Bug]: Microsoft.DataApiBuilder fails to install

### ISSUE THREAD

**Issue by Petri-Leinonen** [Azure/data-api-builder#1553]
### What happened?

I'm trying to install this Microsoft.DataApiBuilder, but it fails every time. I have tried to reinstall the dotnet SDK version 6 (6.0.411) but no luck. Below is the output I'm getting when trying to install. I also tried the install command without version parameter but the same issue prevails.

```
C:\Users\cnpet>dotnet tool install --global microsoft.dataapibuilder --version 0.7.6
C:\Users\cnpet\AppData\Local\Temp\7e81fba7-690c-4fcb-8e00-e2dccbd5089d\restore.csproj : error NU1100: Unable to resolve
 'microsoft.dataapibuilder (>= 0.7.6)' for 'net6.0'.
C:\Users\cnpet\AppData\Local\Temp\7e81fba7-690c-4fcb-8e00-e2dccbd5089d\restore.csproj : error NU1100: Unable to resolve
 'microsoft.dataapibuilder (>= 0.7.6)' for 'net6.0/any'.
The tool package could not be restored.
Tool 'microsoft.dataapibuilder' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```

I have verified that I am running the command on SDK version 6.0.411.

```
C:\Users\cnpet>dotnet --list-sdks
6.0.411 [C:\Program Files\dotnet\sdk]
```

### Version

'dab' is not recognized as an internal or external command, operable program or batch file.

### What database are you using?

Azure SQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Petri-Leinonen** [comment]
I figured this out. The issue was not in the Microsoft.DataApiBuilder package. But for some reason the `dotnet tool install` command couldn't install any packets. I tried some other packets and they gave the same error. But [this](https://github.com/dotnet/sdk/issues/10295#issuecomment-821842586) fixed my issue.

**Comment by seantleonard** [comment]
Hi @Petri-Leinonen , Glad you resolved the issue you were seeing. 

You can also install a locally downloaded NuGet package. The only odd behavior is the NuGet source must be a folder that contains the NuGet package per https://github.com/dotnet/sdk/issues/13429#issuecomment-783995259. 

`dotnet tool install --global --add-source <package-enclosing-folder> Microsoft.DataApiBuilder --version <example: e.g. 0.8.103-97145284>`
