### ISSUE TITLE
[Bug]: DataApiBuilder SIGTERM with Exec format error when run via SWA

### ISSUE THREAD

**Issue by Cypher1** [Azure/data-api-builder#1560]
### What happened?

```
[dataApi] /bin/sh: 1: /home/jaypratt/.swa/dataApiBuilder/0.7.6/Microsoft.DataApiBuilder: Exec format error
```

Exec format error when running data api builder via `swa` with
```
swa start http://localhost:5173 --run "npm run frontend" --api-location api --data-api-location swa-db-connections
```

On Linux Mint

### Version

No dab found (Running via SWA)

### What database are you using?

PostgreSQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST, GraphQL

### Relevant log output

```Text
> swa start http://localhost:5173 --run "npm run frontend" --api-location api --data-api-location swa-db-connections


Welcome to Azure Static Web Apps CLI (1.1.3)

***********************************************************************
* WARNING: This emulator may not match the cloud environment exactly. *
* Always deploy and test your app in Azure.                           *
***********************************************************************

[dataApi] /bin/sh: 1: /home/jaypratt/.swa/dataApiBuilder/0.7.6/Microsoft.DataApiBuilder: Exec format error
[dataApi] cd "/home/jaypratt/skfltech/skfl/swa-db-connections" && "/home/jaypratt/.swa/dataApiBuilder/0.7.6/Microsoft.DataApiBuilder" start -c staticwebapp.database.config.json --no-https-redirect exited with code 126
--> Sending SIGTERM to other processes..
[swa] node "/home/jaypratt/skfltech/skfl/node_modules/@azure/static-web-apps-cli/dist/msha/server.js" exited with code SIGTERM
--> Sending SIGTERM to other processes..
[run] cd "/home/jaypratt/skfltech/skfl" && npm run frontend exited with code SIGTERM
--> Sending SIGTERM to other processes..
[api] cd "/home/jaypratt/skfltech/skfl/api" && "func" start --cors "*" --port 7071  exited with code SIGTERM
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Cypher1** [comment]
Seems related to the error here: https://github.com/Azure/static-web-apps-cli/issues/710

**Comment by seantleonard** [comment]
Thank you for reporting, @Cypher1. We will investigate whether any components in the DAB engine needs to be updated to remediate the experience versus a fix in the Static Web Apps CLI.

**Comment by Aniruddh25** [comment]
hi @Cypher1, could you please try workaround by manually downloading the linux zip bits and extracting them where SWA needs it? I think issue is with the SWA CLI and probably, this PR fixes it as well: https://github.com/Azure/static-web-apps-cli/pull/718

**Comment by Cypher1** [comment]
Awesome! @Aniruddh25 Really appreciate this.

SWA haven't updated their releases yet
Could you point me at an updated download? I tried building from source?

**Comment by Aniruddh25** [comment]
Adding @thomasgauvin to direct on SWA CLI bits

**Comment by thomasgauvin** [comment]
The fix was found and it'll come out in the next SWA CLI release!

**Comment by cjk7989** [comment]
A new version of swa-cli v1.1.4 has been published that fixes the issue. Sorry for the delay and thanks for your feedback.

**Comment by Aniruddh25** [comment]
Linking the release tag here https://github.com/Azure/static-web-apps-cli/releases/tag/v1.1.4 and closing. Please reopen in swa repo if this doesnt fix the issue. Thanks!
