### ISSUE TITLE
Minimum supported database versions for each database type

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#1562]
Determine the minimum supported version for each database type when used with DAB and document the information in the user facing docs.
```[tasklist]
### Tasks
```

**Comment by JerryNixon** [comment]
Related #1537

**Comment by JerryNixon** [comment]
Starter grid: @severussundar 

|DB|MIN VER|
|-|-|
|Azure SQL|n/a|
|CosmosDB|n/a|
|SQL Server|?|
|MySQL|8|
|Postgres|?|

**Comment by JerryNixon** [comment]
https://learn.microsoft.com/en-us/azure/data-api-builder/database-specific-features
