### ISSUE TITLE
OpenAPI - Document Auth N/Z components 

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#1573]
## Summary
- In the `OpenApiDocumentor` service
  - Enable documenting the `x-ms-api-role` header, making it an optional header the user can fill when using the SwaggerUI, such that they can define the role context of a request.
  -  Enable documenting the Authorize header with value `Bearer <access_token>`
    - This may require documenting an oauth flows object (authorize code flow) https://spec.openapis.org/oas/v3.0.1#oauth-flows-object so that sign-in/token acquisition can occur.

### Resources
- https://swagger.io/docs/specification/authentication/
- https://spec.openapis.org/oas/v3.0.1#header-object
- https://spec.openapis.org/oas/v3.0.1#fixed-fields-22

**Comment by ayush3797** [comment]
I am not sure if we can facilitate token acquisition via swagger UI. Reason being, token acquisition needs information like `authorizationUrl`,`tokenUrl`,`refreshUrl` etc. to be known in the OpenAPI specs. For us, we are deriving the specs from the runtime config file and the metadata of the entities. So, to say, we need to know things like `authorizationUrl`,`tokenUrl`,`refreshUrl` etc. beforehand in something like runtime config file, which I don't think we want to do. 

This is very similar to postman where to acquire jwt token, we provide the value of `authorizationUrl`,`callbackUrl` etc while executing the request.

**Comment by seantleonard** [comment]
needs additional input

**Comment by JerryNixon** [comment]
Will recreate issue with more detail and up to date information when ready.
