### ISSUE TITLE
Add support for defining a limit in how nested queries can be

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1577]
Currently, we do not limit the amount of nesting in our graphQl queries, which can result in long running queries.

**Things to keep in mind:**
1.  Find the limiting depth such that a balance is maintained between limiting nesting depth and maintaining query flexibility.
2. Keep the Client Experience in mind. Deeply nested queries can provide more granular data, but they may also make the client code more complex.
3. Make sure to test the GraphQL queries, both within the nesting limit and at the limit's boundaries. Monitor query performance and resource usage to identify any bottlenecks or issues that may arise from the imposed nesting limit.

**Comment by michaelstaib** [comment]
Adding a limit is often not enough for GraphQL APIs... with Hot Chocolate 14 we are introducing a lot of security policies to Hot Chocolate. One thing that  might also be interesting to you is the IBM Cost Spec which allows to prevent threads, rate limiting and other things but also allows to better charge consumers for the impact they had to the system:
https://github.com/ChilliCream/graphql-platform/pull/7146

The cost spec will enable:
- Threat Protection
- Rate Limiting
- Monetization

you can read up here:
https://ibm.github.io/graphql-specs/

**Comment by michaelstaib** [comment]
If you want to have a look at GraphQL security and what we will do in HC14 to simplify security for the user ... give me a ping.

**Comment by michaelstaib** [comment]
Once I have HC 14 done we can have a look at migration together.
