### ISSUE TITLE
[Enhancement]: Add validate to the CLI

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1579]
This is a proposal for adding `validate` to the CLI.

## Example

`dab validate config.json`

## Reasoning

Longer config JSON files can be difficult to read for errors. We use the CLI, but sometimes manual interaction with the file is necessary. The current (not ideal) approach is to validate a config file is to deploy or start dab to see if there are errors as a result. Using this new `validate` command can run the same logic already implemented in deploy and start but returns in design time.

## Benefits

1. The **developer experience** is nicer because `validate` can include in its error message the line number.'
2. The **devops experience** is nicer because configs can be validated as a command line gate operation.

**Comment by abhishekkumams** [comment]
completed in #1856
