### ISSUE TITLE
[Improvement] In startup.cs fix filename references to logs

### ISSUE THREAD

**Issue by rohkhann** [Azure/data-api-builder#1591]
There are references to filenames in logs which make sense as of now but may need refactoring. 

```[tasklist]
### Tasks
- Clean up logs using filename and replace as applicable.
```

```[tasklist]
### Tasks
```

**Comment by aaronpowell** [comment]
Should we close this one in favour of https://github.com/Azure/data-api-builder/issues/1593?

**Comment by rohkhann** [comment]
Closing and work being tracked by #1593
