### ISSUE TITLE
[Bug]: when primary key fields are included in REST payloads, DAB throw exceptions

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1592]
### What happened?

In REST insert and update ops, keys are included in the URL path. **However, if those same key fields are included in the inbound payload DAB returns an exception.** 

This exception is unnecessary and should be considered a bug. There are two reasons for this: First, having the keys in the payload does not cause any conflicts or problems. Second, handling this situation creates unnecessary complexity for .NET developers, requiring them to dynamically remove properties from their models at runtime or maintain separate models for inbound and outbound data. This leads to code bloat and increased requirements for tooling, testing, and code quality. 

**The solution is simple: Ignore the key fields in the posted payload if they are present.** I would also recommend that we ignore their value. If, for example, they post values differing from those in the URL, we do not do a comparison, we simply ignore what is in the posted payload altogether. 

### Version

Microsoft.DataApiBuilder 0.6.13+32fc03f4fe439d02aef454f10cc58e50d0d29f79

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Associate with PR and close. this is `rest-request-strict` feature.

**Comment by seantleonard** [comment]
RFC: #1606 
PullRequest: #1608
