### ISSUE TITLE
Provide an API to GET runtime config file (from local file system)

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1622]

**Comment by aaronburtle** [comment]
Work still not started on this task. It is prioritized behind the Hot Reload refactor and the adding of log-level to config


https://github.com/Azure/data-api-builder/issues/1966

https://github.com/Azure/data-api-builder/issues/1645

**Comment by seantleonard** [comment]
Identify how to merge the hackathon project.

**Comment by seantleonard** [comment]
Needs more discussion on design, background on what problem we're solving here
