### ISSUE TITLE
[Bug]: Using filter on multi-level nested objects causes runtime error (GraphQL, CosmosDB)

### ISSUE THREAD

**Issue by Isayaa** [Azure/data-api-builder#1628]
### What happened?

**Simplified version of the schema looks like:**

```
type EmployeeAggregate @model {
  id: ID
  Payload: Payload
}

type Payload {
  Id: ID
  Jobs: [Job]
}

type Job {
  Fte: Int
}
```

**Config looks like:**
```
"entities": {
    "EmployeeAggregate": {
      "source": "employeeAggregates_v2",
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "*"
          ]
        }
      ]
    },
    "Payload": {
      "source": "employeeAggregates_v2",
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "*"
          ]
        }
      ]
    },
    "Job": {
      "source": "employeeAggregates_v2",
      "graphql": {
        "type": {
          "singular": "Job",
          "plural": "Jobs"
        }
      }
	}
}
```

**Query looks like:**
```query EmployeeAggregates {
    employeeAggregates(first: 10, filter: {Payload: {Jobs: {Fte: {eq: 1}}}}) {
        items {
            Payload {
                Id
            }
        }
    }
}
```

**Error looks like:**
```
{
    "errors": [
        {
            "message": "GraphQL type doesn't match any entity name or singular type in the runtime config.",
            "extensions": {
                "code": "BadRequest"
            }
        }
    ]
}
```

**Note**
Filtering on first-level nested object (e.g. "Payload") works. However, filtering second-level nested objects (e.g. "Jobs") fails.

### Version

0.7.6

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
{
    "errors": [
        {
            "message": "GraphQL type doesn't match any entity name or singular type in the runtime config.",
            "extensions": {
                "code": "BadRequest"
            }
        }
    ]
}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Isayaa** [comment]
This problem is similar to issue #1538, but the provided solution doesn't work in this case.

**Comment by seantleonard** [comment]
Thank you for reporting. We will investigate. CC @tarazou9 @mbhaskar

**Comment by tarazou9** [comment]
@Isayaa Thank you for reporting and letting us know! We currently only support first-level nested object filtering for Cosmos DB, it's mentioned here in this [PR](https://github.com/Azure/data-api-builder/pull/1468)'s description note. We are working on updating the documentation for this current limitation @sajeetharan

**Comment by Isayaa** [comment]
@tarazou9 thanks for your answer. Some feedback and question:
- Your PR only mentions a limitation with mutations. However, in this case we just need to have the queries working. Is it a mistake in the PR description?
- Do you have any plan in fixing the limitation (for queries)? It's an important info for us because it would mean we need to consider another technology to expose our existing CosmosDB that contains nested objects up to 3 level.

**Comment by sajeetharan** [comment]
@Isayaa This limitation extends to queries as well. We will assess and provide you with an update regarding the ETA for the fix."

**Comment by Isayaa** [comment]
@sajeetharan any update on the ETA for this ?

**Comment by jmkelljr** [comment]
Was this issue ever fixed?  I'm running into the same issue trying to query filter on an Author last_name for dab version 0.9.7 against cosmos db for the Books/Authors example.  First level filter queries on things like "title" work fine.

schema:
type Book @model {
  id: ID
  title: String
  Authors: [Author]
}

type Author {
  id: ID
  first_name: String
  middle_name: String
  last_name: String
}

query:
query Books {
    books(filter: { Authors: { last_name: { contains: "Asimov" } } }) {
        items {
            id
            title
            Authors {
                id
                first_name
                middle_name
                last_name
            }
        }
    }
}

error:
fail: Azure.DataApiBuilder.Service.Startup[0]
      A GraphQL request execution error occurred.
      Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: GraphQL type doesn't match any entity name or singular type in the runtime config.
         at Azure.DataApiBuilder.Core.Services.MetadataProviders.CosmosSqlMetadataProvider.GetEntityName(String graphQLType) in /src/src/Core/Services/MetadataProviders/CosmosSqlMetadataProvider.cs:line 338
         at Azure.DataApiBuilder.Core.Models.GQLFilterParser.Parse(IMiddlewareContext ctx, IInputField filterArgumentSchema, List`1 fields, BaseQueryStructure queryStructure) in /src/src/Core/Models/GraphQLFilterParsers.cs:line 206
         at Azure.DataApiBuilder.Core.Resolvers.CosmosQueryStructure.Init(IDictionary`2 queryParams) in /src/src/Core/Resolvers/CosmosQueryStructure.cs:line 168
         at Azure.DataApiBuilder.Core.Resolvers.CosmosQueryStructure..ctor(IMiddlewareContext context, IDictionary`2 parameters, ISqlMetadataProvider metadataProvider, IAuthorizationResolver authorizationResolver, GQLFilterParser gQLFilterParser) in /src/src/Core/Resolvers/CosmosQueryStructure.cs:line 43
         at Azure.DataApiBuilder.Core.Resolvers.CosmosQueryEngine.ExecuteAsync(IMiddlewareContext context, IDictionary`2 parameters, String dataSourceName) in /src/src/Core/Resolvers/CosmosQueryEngine.cs:line 63
         at Azure.DataApiBuilder.Core.Services.ResolverMiddleware.InvokeAsync(IMiddlewareContext context) in /src/src/Core/Services/ResolverMiddleware.cs:line 106
         at HotChocolate.Utilities.MiddlewareCompiler`1.ExpressionHelper.AwaitTaskHelper(Task task)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
         at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]

dab-config
{
    "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.9.7/dab.draft.schema.json",
    "data-source": {
      "database-type": "cosmosdb_nosql",
      "connection-string": "AccountEndpoint=<removed....>",
      "options": {
        "database": "PlaygroundDB",
        "container": "books",
        "schema": "/myfiles/schema.gql"
      }
    },
    "runtime": {
      "rest": {
        "enabled": false,
        "path": "/api",
        "request-body-strict": true
      },
      "graphql": {
        "enabled": true,
        "path": "/graphql",
        "allow-introspection": true
      },
      "host": {
        "mode": "development",
        "cors": {
          "origins": [],
          "allow-credentials": false
        },
        "authentication": {
          "provider": "StaticWebApps"
        }
      }
    },
    "entities": {
      "Author": {
        "source": "authors",
        "rest": false,
        "graphql": true,
        "permissions": [
          {
            "role": "anonymous",
            "actions": [ "*" ]
          }
        ]
      },
      "Book": {
        "source": "books",
        "rest": false,
        "graphql": true,
        "permissions": [
          {
            "role": "anonymous",
            "actions": [ "*" ]
          }
        ]
      }
    }
  }

**Comment by neeraj-sharma2592** [comment]
hi @jmkelljr , It hasn't been resolved yet. I'll keep you informed as soon as the fix is implemented.

**Comment by jmkelljr** [comment]
Thank you!
