### ISSUE TITLE
[Bug]: datetime2 field in utc from Azure SQL is returned in locale (i.e. +03:00)

### ISSUE THREAD

**Issue by vmtorn** [Azure/data-api-builder#1631]
### What happened?

fields in Azure SQL (date column is of type datetime2 ) are:
 "ID": 1068357,
 "SensorID": "486948495",
  "date": "2023-08-08T12:04:07.686",

DAB returns following, with Insomnia: 
{
	"SensorID": "486948495",
         "value1": 18.06,
	"unit1": "°C (probe)",
	"date": "2023-08-08T12:04:07.686+03:00"
}
It should be Z or +00:00?

### Version

0.7.6

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Thank you for reporting, we will investigate CC: @abhishekkumams
