### ISSUE TITLE
[Bug]: Wrong REST path generated in OpenAPI spec

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#1633]
### What happened?

When adding the entity via DAB CLI, the generated path for REST contains an unescaped slash. This is the DAB CLI command I used:

```
dab add Todos --source dbo.todos --permissions "anonymous:*" --rest todos
```

and this is the configuration I got for the created entity:

```
"Todos": {
      ...
      "rest": {
        "enabled": true,
        "path": "/todos",
        "methods": [
          "get",
          "post",
          "put",
          "patch",
          "delete"
        ]
      },
    ...
    }
```

the path at which REST API are available is:

```
/api/odos
```

instead of the correct:

```
/api/Todos
```

### Version

Microsoft.DataApiBuilder 0.8.44-rc+ebe4ef414deaf7670b579fe160b872c6b682c114

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JerryNixon** [comment]
But you escape characters in JSON with a backslash, not a forward slash.

**Comment by Aniruddh25** [comment]
I cant reproduce this issue. Could you please double check?

**Comment by yorek** [comment]
> But you escape characters in JSON with a backslash, not a forward slash.

Yeah, I think the problem is not in the JSON, but on how the slash is used to generate the REST endpoint. If the slash is not there, everything works as expected.

**Comment by yorek** [comment]
> I cant reproduce this issue. Could you please double check?

Just checked, here's the detailed repro: 

```
dotnet tool install Microsoft.DataApiBuilder -g --prerelease
dab init --database-type mssql --host-mode development --connection-string "@env('MSSQL')"
dab add Todos --source dbo.todos --permissions "anonymous:*" --rest todos
```

**Comment by Aniruddh25** [comment]
After syncing offline, found that the wrong path is generated in the OpenAPI spec - not as an actual endpoint.
