### ISSUE TITLE
RFC: Multiple data sources

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1638]
# Summary
Allow a single DAB instance to interact with multiple backend data sources. 

# Motivation
This design enables DAB to address more sophisticated customers.

# Old behavior
Currently, DAB supports only a single `data source` and a single `dab-config.json` file. 

## Barriers to multiple data sources: 
1. The `data-source` property in the config is of type `object`, not `array`. 
2. The `data-source` property in the config applies to every `entity`.  

# New behavior
Support the use of multiple `dab-config.json` files, each corresponding to a different `data-source`, to merge at runtime. 

⭐ When DAB starts, the GLOBAL and CHILD files will be merged. 

## Design goals:
1. A single `dab-config.json` file must always be viable in DAB. 
1. We will not impose arbitrary limits on `data-source` or `entities` at this time. 
1. Developers must easily understand which file has an error. 
1. `entity` names across all files must be unique to support future features. 

## Sample global file
````json
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.7.6/dab.draft.schema.json",
  "data-source-files": [
     "dab-config.mssql-hr.json",
     "dab-config.cosmosdb-sales.json",
     "dab-config.mysql-inventory.json",
     "dab-config.postgres-shipping.json",
   ],
  ...
}
````

## Global file characteristics
1. The global file must have `runtime` properties.
1. The global file's `data-source` property is optional. 
1. The global file's `data-source-files` property is optional. 
1. Paths in `data-source-files` may include Unicode characters. 

## New `data-source-files` property in JSON schema.
````json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "data-source-files": { // new property
      "type": "array",
      "description": "Child file paths",
      "items": {
        "type": "string"
      },
      "default": []
  }
}
````

This new property, of type `string[]`, is optional. If the `data-source-files` property is `[]` or omitted, the `data-source` property is required. Otherwise, the `data-source` property is optional. 

## Path translation
When filled, the `data-source-files` property contains _paths_ to child files. These paths can include dots `.` and slashes `/` & `\`, indicating the location of the child file relative to the global config file. 

If the global config file is at `c:\web\api\dab-config.json`, then:

|Path in Config|File Location|
|-|-
|`dab-config.02.json`|`c:\web\api\dab-config.02.json`
|`./dab-config.03.json`|`c:\web\api\dab-config.03.json`
|`../dab-config.04.json`|`c:\web\dab-config.04.json`
|`/other/dab-config.05.json`|`c:\web\api\other\dab-config.05.json`
|`../web/dab-config.06.json`|`c:\web\api\dab-config.06.json`

# Child file characteristics

1. A child file must have a `data source` defined.
1. A child file may define `data-source-files`, which can be thought of as "grandchild" files. 
1. A child file may be used as a global file if it has `runtime` properties set. 
1. If a child file has `runtime` properties, they will be ignored; the global file is always used. 
1. A child file can be named anything and be located in any accessible folder relative to the global file.

**Comment by kliszaq** [comment]
@JerryNixon as the requirement is under development, is there a chance to extend it a little bit to "more than sophisticated" customers regarding the routing of the api ?
Currently, according to the specification, if the entity name doubles in the two data sources, the entity name needs to be replaced manually by the customer. For the automated tools that generate APIs based on the database metadata for different databases, it would be required to add the prefix or suffix per database for the entity name, like Db1_User, Db2_User.
I propose to use the urls to distinguish between the child databases, like /api/db1/user, /api/db2/user, etc. The root /api/user would refer to the global configuration file.

Is it possible to change that piece of the functionality?

kind regards,
Kamil

**Comment by JerryNixon** [comment]
This is complete. @rohkhann we believe this was completed for both GQL and REST, which is why it was left open.
