### ISSUE TITLE
Evaluate consecutive slashes in a URL

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#1640]
Consider a URL such as `https://localhost:5001//api/Book`. Although this is a valid URL, evaluate whether DAB should allow this way of accessing the `Book` entity.

At the moment, a 400 error is returned.

![image](https://github.com/Azure/data-api-builder/assets/11196553/ec4b6ac2-edeb-4aaf-896a-e542262bc9b8)

Evaluate and come up with 
a) Whether we want to allow such a request ? 
b) The exact error status code and message in case such a request is not to be allowed

**Comment by ayush3797** [comment]
https://stackoverflow.com/questions/10161177/url-with-multiple-forward-slashes-does-it-break-anything

**Comment by seantleonard** [comment]
> https://stackoverflow.com/questions/10161177/url-with-multiple-forward-slashes-does-it-break-anything

I agree that multiple slashes in a row is valid syntactically per spec. However, this issue poses the question of how DAB should evaluate multiple slashes in a row: e.g. is example 1 equal to example 2:

1. `<dab_server:port>/api/entity//pk//pk_value`
2. `<dab_server:port>/api/entity/pk/pk_value`

In my opinion, example 1 is not a valid way to make requests against `entity` with primary key `pk` of value `pk_value`. 

Either a 400 bad request is warranted, or 404 not found.

**Comment by seantleonard** [comment]
To elaborate on bullet point 1 in my previous comment: it reads as follows:
`/entity//pk//pk_value`

- Entity: `entity`
- PK_Name1: ``
- PK_Value1: `pk`
- PK_Name2: ``
- PK_Value2: `pk_value`

Which is invalid. In this particular example, 400 bad request may be more applicable because `entity` is a valid entity, but the formation of the pk part of the path is wrong.

For 404, this example would be in scope `<dab_server:port>/api//entity/pk/pk_value`
1. entity name `` doesn't exist
2. all the path afterwards is irrelevant because you wouldn't have an entity to check primary key /value pairs against anyway.

**Comment by seantleonard** [comment]
last note to consider for if/when this change is made : we'll need to update openapidocumentor to take this into account because of the use of Trim('/') which is also present in the dab engine.

**Comment by abhishekkumams** [comment]
what if we do want to provide an empty string as path value? In that case '//' cannot be same as '/'.

**Comment by JerryNixon** [comment]
Seems like we should comply with [rfc2396](https://www.ietf.org/rfc/rfc2396.txt). 

````TXT
3. URI Syntactic Components

   The URI syntax is dependent upon the scheme.  In general, absolute
   URI are written as follows:

      <scheme>:<scheme-specific-part>

   An absolute URI contains the name of the scheme being used (<scheme>)
   followed by a colon (":") and then a string (the <scheme-specific-
   part>) whose interpretation depends on the scheme.

   The URI syntax does not require that the scheme-specific-part have
   any general structure or set of semantics which is common among all
   URI.  However, a subset of URI do share a common syntax for
   representing hierarchical relationships within the namespace.  This
   "generic URI" syntax consists of a sequence of four main components:

      <scheme>://<authority><path>?<query>

   each of which, except <scheme>, may be absent from a particular URI.
   For example, some URI schemes do not allow an <authority> component,
   and others do not use a <query> component.

      absoluteURI   = scheme ":" ( hier_part | opaque_part )

   URI that are hierarchical in nature use the slash "/" character for
   separating hierarchical components.  For some file systems, a "/"
   character (used to denote the hierarchical structure of a URI) is the
   delimiter used to construct a file name hierarchy, and thus the URI
   path will look similar to a file pathname.  This does NOT imply that
   the resource is a file or that the URI maps to an actual filesystem
   pathname.

      hier_part     = ( net_path | abs_path ) [ "?" query ]

      net_path      = "//" authority [ abs_path ]

      abs_path      = "/"  path_segments

   URI that do not make use of the slash "/" character for separating
   hierarchical components are considered opaque by the generic URI
   parser.

      opaque_part   = uric_no_slash *uric

      uric_no_slash = unreserved | escaped | ";" | "?" | ":" | "@" |
                      "&" | "=" | "+" | "$" | ","

   We use the term <path> to refer to both the <abs_path> and
   <opaque_part> constructs, since they are mutually exclusive for any
   given URI and can be parsed as a single component.
````

Also

````TXT
3.2. Authority Component

   Many URI schemes include a top hierarchical element for a naming
   authority, such that the namespace defined by the remainder of the
   URI is governed by that authority.  This authority component is
   typically defined by an Internet-based server or a scheme-specific
   registry of naming authorities.

      authority     = server | reg_name

   The authority component is preceded by a double slash "//" and is
   terminated by the next slash "/", question-mark "?", or by the end of
   the URI.  Within the authority component, the characters ";", ":",
   "@", "?", and "/" are reserved.
````

Also

````TXT
3.3. Path Component

   The path component contains data, specific to the authority (or the
   scheme if there is no authority component), identifying the resource
   within the scope of that scheme and authority.

      path          = [ abs_path | opaque_part ]

      path_segments = segment *( "/" segment )
      segment       = *pchar *( ";" param )
      param         = *pchar

      pchar         = unreserved | escaped |
                      ":" | "@" | "&" | "=" | "+" | "$" | ","

   The path may consist of a sequence of path segments separated by a
   single slash "/" character.  Within a path segment, the characters
   "/", ";", "=", and "?" are reserved.  Each path segment may include a
   sequence of parameters, indicated by the semicolon ";" character.
   The parameters are not significant to the parsing of relative
   references.
````

**Comment by seantleonard** [comment]
Not planned. DAB shouldn't guess what the user means here. The initial issue summary references an invalid route for a specific entity.
