### ISSUE TITLE
Add `log-level` property to runtime config schema

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1645]
This Issue is to propose a new property called `log-level` under the runtime section of dab config file to specify the minimum logging level in our Application. for example if it is set to `Information`, trace and debug logs won't be displayed while warning and errors along with Information Logs will show up.
Having LogLevel specified in the config file enable users to specify the logLevel when CLI is not envolved(where we can use --LogLevel).

```
{
  "runtime": {
    ...
    "log-level": "Information",
    ...
}
```

This logLevel will be used for logging in the console as well as sending logs to Applicaiton Insights.

**Comment by seantleonard** [comment]
#1829

**Comment by seantleonard** [comment]
Moving this + hot reload related tasks to post GA -> tracking via 1.2rc milestone.

**Comment by seantleonard** [comment]
Lower priority because you can set log level via argument to dab.exe process 
```sh
$ ./Microsoft.DataApiBuilder --LogLevel Information
```
