### ISSUE TITLE
Multiple Create - Database Query Generation and Selection Set Resolution

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#1699]
Implement the changes to generate the necessary database queries to successfully perform a multiple create mutation

Related Issue: [Database Query Generation Design - [Multiple Create - Query Generation design](https://github.com/Azure/data-api-builder/issues/1887)

**Comment by seantleonard** [comment]
needs consolidation of code from AuthZ nested mutation pr and config-only defined relationship support.
