### ISSUE TITLE
Evaluate the rollout mechanism of nested mutations 

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#1701]
1. Evaluate and come up with a way so that the new DAB versions support nested mutations and also remain backward compatible

2. Evaluate and come up with an approach for the development workflow/lifecycle for the feature.
3. Evaluate whether a feature flag is needed for nested mutations after release - i.e provide users the ability to hide/turn off the nested mutations feature if needed?

**Comment by ayush3797** [comment]
We will be merging all the sub-tasks (Schema Generation, Authorization, Request validation, Database Query Generation) into the feature branch: [dev/NestedMutations](https://github.com/Azure/data-api-builder/tree/dev/NestedMutations).

We would need a feature flag for enabling nested mutations (by default support for nested mutations would be off).

**Comment by severussundar** [comment]
> We will be merging all the sub-tasks (Schema Generation, Authorization, Request validation, Database Query Generation) into the feature branch: [dev/NestedMutations](https://github.com/Azure/data-api-builder/tree/dev/NestedMutations).
> 
> We would need a feature flag for enabling nested mutations (by default support for nested mutations would be off).

Shouldn't the feature be **enabled** by default?

**Comment by seantleonard** [comment]
all questions answered here. Feature flag work continued in separate issue and other two questions decided.
