### ISSUE TITLE
[Bug]: Docs link in Registry is incorrect

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1711]
### What happened?

The Registry uses to https://go.microsoft.com/fwlink/?linkid=2224253

This points to the OLD docs and not the NEW docs. 

Registry site: https://mcr.microsoft.com/en-us/product/azure-databases/data-api-builder/

### Version

-

### What database are you using?

Azure SQL

### What hosting model are you using?

Container Apps

### Which API approach are you accessing DAB through?

REST, GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniruddh25** [comment]
This has been fixed.
