### ISSUE TITLE
IP not set on interface

### ISSUE THREAD

**Issue by rtharner** [Azure/data-api-builder#1749]
I created a Windows Container (latest 2022) installed framework6 sdk and installed DAP all worked out well only it seems the interface isnt binding to the correct network interface.

Seems it only listening to the local adapter, any thoughts how to solve this?

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:5985           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:47001          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49152          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49153          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49154          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49155          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49156          0.0.0.0:0              LISTENING
  TCP    127.0.0.1:5000         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:5001         0.0.0.0:0              LISTENING
  TCP    [::]:135               [::]:0                 LISTENING
  TCP    [::]:5985              [::]:0                 LISTENING
  TCP    [::]:47001             [::]:0                 LISTENING
  TCP    [::]:49152             [::]:0                 LISTENING
  TCP    [::]:49153             [::]:0                 LISTENING
  TCP    [::]:49154             [::]:0                 LISTENING
  TCP    [::]:49155             [::]:0                 LISTENING
  TCP    [::]:49156             [::]:0                 LISTENING
  TCP    [::1]:5000             [::]:0                 LISTENING
  TCP    [::1]:5001             [::]:0                 LISTENING
  UDP    0.0.0.0:5353           *:*
  UDP    0.0.0.0:5355           *:*
  UDP    0.0.0.0:65099          *:*
  UDP    127.0.0.1:65100        127.0.0.1:65100
  UDP    [::]:5353              *:*
  UDP    [::]:5355              *:*
  UDP    [::]:65099             *:*

**Comment by seantleonard** [comment]
Hi,
How did you create your container? Can you list steps because there may be configuration made outside of DAB that results in the behavior you are seeing.

**Comment by rtharner** [comment]
Hi Leonard,

Sure, see steps below.

-docker pull mcr.microsoft.com/windows/servercore:ltsc2022
-docker run -d --name DABTEST --hostname DABTEST --network PROD -p 5000/TCP -p 135/TCP -it mcr.microsoft.com/windows/servercore:ltsc2022 cmd.exe
-docker.exe exec -it DABTEST cmd /S /K
-Invoke-WebRequest -OutFile dotnet-sdk-6.0.102-win.exe https://download.visualstudio.microsoft.com/download/pr/fb14ba65-a9c9-49ce-9106-d0388b35ae1b/7bbfe92fb68e0c9330c9106b5c55869d/dotnet-sdk-6.0.102-win-x64.exe;
-Start-Process "dotnet-sdk-6.0.102-win-x64.exe" -ArgumentList "/passive" -wait -Passthru
-dotnet --list-sdks
-dotnet tool install --global Microsoft.DataApiBuilder


Kind regards,
Rogier

**Comment by seantleonard** [comment]
@rtharner, this seems specific to your network and how you configure and deploy Docker/your Docker container. The container looks to be listening to the ports you specified: `--network PROD -p 5000/TCP -p 135/TCP`:
>`TCP [::]:135 [::]:0 LISTENING`
>`TCP [::1]:5000 [::]:0 LISTENING`

Few more questions:

- How are you trying to access DAB, is DAB successfully starting? 
- When you say "interface isnt binding to the correct network interface" what is the behavior you are seeing which indicates that DAB is inaccessible? 
- are you trying to access dab from a browser on your docker host machine?

**Comment by rtharner** [comment]
Hi Leonard,

It's binding to the local loopback adapter (127.0.0.1) i solved it by adding a parameter to the run command.

-e DOTNET_URLS=http://+:5000

**Comment by rtharner** [comment]
Hi Leonard,

It's binding to the local loopback adapter (127.0.0.1) i solved it by adding a parameter to the run command.

-e DOTNET_URLS=http://+:5000
