### ISSUE TITLE
Is it possible to build Docker images manually?

### ISSUE THREAD

**Issue by KaneJU** [Azure/data-api-builder#1752]
### What happened?

I noticed that the docker folder is empty in the repository. Is there a way to build Docker images manually for this project? If so, could you please provide some instructions?

### Version

Lest

### What database are you using?

Azure SQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhishekkumams** [comment]
you can use the below command to build docker image locally
```
docker build -t mydocker:1.0.0 .
```

The `docker build` command can be used to build a Docker image from a Dockerfile. The -t option is used to tag the image with a name and optional tag in the name:tag format. The . at the end of the command specifies the build context, which is the directory containing the Dockerfile and any other files needed to build the image.

In the command docker build -t mydocker ., we are building a Docker image with the name mydocker and the tag (mydocker:1.0.0) from the Dockerfile in the current directory (.).

Once the build is complete, you can use the `docker run` command to create a container from the image and run it.

**Comment by Aniruddh25** [comment]
Since this has been answered, closing this issue, if you still have further questions please open up a discussion thread
