### ISSUE TITLE
[Improvement] Multi-Source Support for REST scenario.

### ISSUE THREAD

**Issue by rohkhann** [Azure/data-api-builder#1753]
with RFC: https://github.com/Azure/data-api-builder/issues/1638, we have added support for multiple datasources for graphql scenario. Pr:https://github.com/Azure/data-api-builder/pull/1709. This issue tracks adding support for multiple datasources for REST scenario.

**Comment by seantleonard** [comment]
Make sure to consider @kliszaq 's points raised in #1761 with regards to how `RestService` maps requests to additional datasources.
