### ISSUE TITLE
Make `entities` an optional property in config

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1757]
Can anyone explain why the entities are mandatory here? When there is not node NRE is thrown.
In the test for RuntimeConfigLoaderJsonDeserializerTests the value  for is empty: ""entities"":{ }. 
**IMHO it should handle null entities node.
BTW: it would be nice to cover edge case - in this case it is the bare minimum global config file.**

_Originally posted by @kliszaq in https://github.com/Azure/data-api-builder/pull/1709#discussion_r1340291104_

**Comment by kliszaq** [comment]
@Aniruddh25 thanks for considering this issue in the dev process. I would like to elaborate on the configuration in context of the multiple databases support. Let's consider two ways we can define the config. I would split the idea into two ways defining the configs:
1) Very clean separation of the config responsibilities: one global file and the database configuration files.
2) Mixed global with the auxiliary configs - it means "main" database connection in the global and also additional endpoints from other databases.

From my point of view the cleanest way to handle the configuration is to support option 1. In such case the global file would contain only **data sources** and the **runtime** sections:
dab-config.json

```
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/0.10.0/dab.draft.schema.json",
  "runtime": {
    "rest": {
      "enabled": true,
      "path": "/api",
      "request-body-strict": true
    },
    "graphql": {
      "enabled": false,
      "path": "/graphql",
      "allow-introspection": true
    },
    "host": {
      "cors": {
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "Production"
    }
  },
  "data-source-files": [
    "dab-config.5.json",
    "dab-config.192.json"
  ]
}
```

while the "slave" configuration does not define the runtime section or is ignored during the file loading.
```
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/0.10.0/dab.draft.schema.json",
  "data-source": {
    "database-type": "MSSQL",
    "connection-string": "***"
  },
  "entities": {
    "adv2012-sales-currencyrate": {
      "source": {
        "object": "[Sales].[CurrencyRate]",
        "type": "View",
        "key-fields": [
          "CurrencyRateID"
        ]
      },
      "graphql": {
        "enabled": false
      },
      "rest": {
        "methods": [
          "Get"
        ],
        "enabled": true
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            {
              "action": "Read"
            }
          ]
        }
      ]
    }
  }
}
```

It means that some of the validation might be done on the JSON schema level, while the other validation needs to be performed during the config loading and the validation.

**Comment by seantleonard** [comment]
We should consider capturing this as a design detail/ requirement of #1638 (@jerrynixon)

**Comment by Aniruddh25** [comment]
hi @kliszaq, 

I see your point about separation of responsibilities - e.g. keeping only the `runtime` section in the global configuration file. 
The only problem in that approach is it would break the single datasource scenario, hence become backwards incompatible. 
So, we chose option 2 - mixed global with auxiliary configs. 

That said, we can certainly remove the restriction of providing `data-source` + `entities` in the global configuration if auxiliary configs are provided in the `data-source-files` property. If they are absent, we would require at least the `data-source` - we can make `entities` optional altogether. 

I hope this makes sense - Let me know if you have further concerns.

Thanks,
Aniruddh.

**Comment by kliszaq** [comment]
Hi @Aniruddh25,
this makes sense.
Thanks,
Kamil

**Comment by JerryNixon** [comment]
The biggest downside to doing this is the sheer complexity of the files now that we support more than one data-source. For example, it is completely valid (or will be) to do this:

* .env
* dab-config.json
  * dab-config1.json
  * dab-config2.json
  * dab-config3.json
  * dab-config4.json 

If environment overrides, we it is completely valid to do this:

* .env
* dab-config.json
* dab-config.development.json
  * dab-config1.json
  * dab-config1.development.json
  * dab-config2.json
  * dab-config2.development.json
  * dab-config3.json
  * dab-config3.development.json
  * dab-config4.json 
  * dab-config4.development.json 

This we add this idea and we could have:

* .env
* dab-config.json
* dab-config-entities.json
* dab-config.development.json
  * dab-config1.json
  * dab-config1-entities.json
  * dab-config1.development.json
  * dab-config2.json
  * dab-config2-entities.json
  * dab-config2.development.json
  * dab-config3.json
  * dab-config3-entities.json
  * dab-config3.development.json
  * dab-config4.json 
  * dab-config4-entities.json 
  * dab-config4.development.json 

**I realize this is doable.** And I realize the point I am about to make is not a technical one. But in the interest of simplicity and approachability, I think we've already introduced considerable sophistication that, though it makes technical sense to do, has already made DAB harder and harder to approach and debug without understanding the ins and outs like a pro. The file structure we chose for multiple data sources was intentionally simplified for this reason, too.

**Comment by JerryNixon** [comment]
@Aniruddh25
As for removing the restriction in the JSON schema, as we move into the `validate` task in this version, making `entities` optional is going to introduce yet another step to ensure that a "typical" developer can have a validation experience that is standard. The only thing I could imagine here is to include something like `dab validate dab-config.json --entities-optional true` so that it could be controlled by the consumer and not by the engine.

**Comment by JerryNixon** [comment]
With the Configurator @Aniruddh25, this seems more relevant again.
