### ISSUE TITLE
REST endpoint support for `$expand` OData query parameter

### ISSUE THREAD

**Issue by sandeepm1980** [Azure/data-api-builder#1760]
### What happened?

$expand not working in REST GET endpoints, Graphql supports querying related entities but REST does not.

### Version

Microsoft.DataApiBuilder 0.8.52+c69925060e1942d28515b9c4b89ea24832da0c7c

### What database are you using?

Azure SQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Hi @sandeepm1980,

The list of currently supported query parameters is here: https://learn.microsoft.com/azure/data-api-builder/rest#query-parameters

We are also tracking improvements for how errors are surfaced for unsupported operations: #354

**Comment by Aniruddh25** [comment]
As @yorek mentioned in the discussion here: https://github.com/Azure/data-api-builder/discussions/1767#discussioncomment-7177015,
we recommend using GraphQL if you would like relationship navigation feature since adding that support to REST would be less performant.

**Comment by hajekj** [comment]
I agree that GraphQL does the job better, but for simple things, where GraphQL is not needed, or simply too complex for people to use (like executing via Power Automate) - an example, where I have a data source which the citizen-developer is connecting to from Canvas Apps...

**Comment by JerryNixon** [comment]
Not on our immediate roadmap. But OData remains interesting. GraphQL serves this need for now.
