### ISSUE TITLE
Change base docker images to Azure Linux

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1762]
The docker base image currently in use are:
Images in use: dotnet/aspnet, dotnet/sdk

Azure Linux(Mariner based) images are: dotnet/aspnet:8.0-preview-cbl-mariner2.0, dotnet/sdk:8.0-preview-cbl-mariner2.0

This issue is to move the currently in use docker base images to Azure Linux images. Once moved, ensure all references use the new Azure Linux based images.

**Comment by AbhijithGanesh** [comment]
@Aniruddh25 This looks like an issue which I can work on! It is not a sophisticated issue I feel. Can I work on it?

**Comment by Aniruddh25** [comment]
For sure, please go ahead! Thank you for the interest and look forward to your contributions!! Assigned this to you.

**Comment by AbhijithGanesh** [comment]
Thanks mate

**Comment by AbhijithGanesh** [comment]
I am adding this here for the future reference:

[CBL-Mariner Repo](https://github.com/microsoft/CBL-MarinerTutorials/tree/main/build-in-container)

**Comment by AbhijithGanesh** [comment]
> The docker base image currently in use are: Images in use: dotnet/aspnet, dotnet/sdk
> 
> Azure Linux(Mariner based) images are: dotnet/aspnet:8.0-preview-cbl-mariner2.0, dotnet/sdk:8.0-preview-cbl-mariner2.0
> 
> This issue is to move the currently in use docker base images to Azure Linux images. Once moved, ensure all references use the new Azure Linux based images.

Heyy, there isn't an Azure Dotnet Image which is currently built on top of CBL-Mariner. I can make an image but ideally for this image should be on mcr.microsoft.com. So I'd like to know if we can add a follow up issue which will allow us to have an image on the artifact registry @Aniruddh25

**Comment by AbhijithGanesh** [comment]
# Question

@Aniruddh25 I wonder if there exists a dotnet image that is built on top of Mariner Linux. I am currently building one but I think there should be a dotnet image that is built on top of mariner

**Comment by AbhijithGanesh** [comment]
```bash
197.8 /src/src/Core/Azure.DataApiBuilder.Core.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/src/Service/Azure.DataApiBuilder.Service.csproj]
197.8 /src/src/Service/Azure.DataApiBuilder.Service.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
197.8 /src/src/Service/Azure.DataApiBuilder.Service.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
197.8 /src/src/Core/Azure.DataApiBuilder.Core.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/src/Service/Azure.DataApiBuilder.Service.csproj]
197.8 /src/src/Service/Azure.DataApiBuilder.Service.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
197.8 /src/src/Core/Azure.DataApiBuilder.Core.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/src/Service/Azure.DataApiBuilder.Service.csproj]
197.8 /src/src/Core/Azure.DataApiBuilder.Core.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json. [/src/src/Service/Azure.DataApiBuilder.Service.csproj]
197.8 /src/src/Service/Azure.DataApiBuilder.Service.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
197.8 /src/src/Service/Azure.DataApiBuilder.Service.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.
```

Can any C# Guru/DotNet dev explain me how I navigate this ? This happens to be an Azure Mariner issue!

I tried both [tdnf](https://vmware.github.io/photon/assets/files/html/3.0/photon_admin/tdnf.html) and [rpm](https://rpm.org/)

**Comment by seantleonard** [comment]
Hey @AbhijithGanesh  What steps are you performing to get to all those errors?  

This might have to do with our custom nuget source, which may be restricting the ability to use public Nuget.org for package restore. You can remove our custom nuget source in your local environment from within this nuget.config file in the root of the repo: https://github.com/Azure/data-api-builder/blob/main/Nuget.config

You can modify the package source to be `https://api.nuget.org/v3/index.json`  (per this thread on stackoverflow: https://stackoverflow.com/a/69045467)

**Comment by AbhijithGanesh** [comment]
Hey @seantleonard! I'm running these commands
```Dockerfile
FROM mcr.microsoft.com/cbl-mariner/base/core:2.0 AS build


RUN tdnf install -y dotnet-sdk-6.0

WORKDIR /src
COPY . .
RUN dotnet build "./src/Service/Azure.DataApiBuilder.Service.csproj" -c Docker -o /out -r linux-x64

```


I am trying to build the main service and it gets blocked!

**Comment by seantleonard** [comment]
hard to say if this is a dab config issue or something in the mariner build chain/your environment. 
When troubleshooting, can you add the option `--verbosity diag` to your dotnet build cmd? Maybe more explanation for why nuget loading fails may be printed to console.

`RUN dotnet build "./src/Service/Azure.DataApiBuilder.Service.csproj" -c Docker -o /out -r linux-x64 --verbosity diag`

or before dotnet build, run diagnostics on why dotnet restore fails:
`dotnet restore --verbosity detailed` https://stackoverflow.com/q/73188295

**Comment by AbhijithGanesh** [comment]
I'll try this out! but I think this one has to do with Mariner

**Comment by AbhijithGanesh** [comment]
```bash
184.0                      Checking compatibility of packages on net6.0. (TaskId:95)
184.0                      All packages and projects are compatible with net6.0. (TaskId:95)
184.0                      Checking compatibility of packages on net6.0 (linux-x64). (TaskId:95)
184.0                      All packages and projects are compatible with net6.0 (linux-x64). (TaskId:95)
184.0                      Committing restore... (TaskId:95)
184.0                      Generating MSBuild file /src/src/Product/obj/Azure.DataApiBuilder.Product.csproj.nuget.g.props. (TaskId:95)
184.0                      Generating MSBuild file /src/src/Product/obj/Azure.DataApiBuilder.Product.csproj.nuget.g.targets. (TaskId:95)
184.0                      Writing assets file to disk. Path: /src/src/Product/obj/project.assets.json (TaskId:95)
184.0                      Writing cache file to disk. Path: /src/src/Product/obj/project.nuget.cache (TaskId:95)
184.0                      Persisting dg to /src/src/Product/obj/Azure.DataApiBuilder.Product.csproj.nuget.dgspec.json (TaskId:95)
184.0                      Failed to restore /src/src/Product/Azure.DataApiBuilder.Product.csproj (in 11.83 sec). (TaskId:95)
184.0 18:25:38.749     1>/src/src/Service/Azure.DataApiBuilder.Service.csproj : error NU1301: Unable to load the service index for source https://api.nuget.org/v3/index.json.```

**Comment by AbhijithGanesh** [comment]
# Update

I understood what needs to be done! As @seantleonard mentioned! **The custom source needs to be added to NuGet**

that is


```dockerfile
RUN dotnet nuget add source https://pkgs.dev.azure.com/sqldab/fcb212b3-b288-4c9e-b55a-5842a268b16d/_packaging/data_api_builder_build_packages/nuget/v3/index.json
```

**Comment by AbhijithGanesh** [comment]
Thanks for this @Aniruddh25 ! This is extremely useful! The PR will be up in a bit!
