### ISSUE TITLE
Feature Request: Hooks and events

### ISSUE THREAD

**Issue by hajekj** [Azure/data-api-builder#1765]
It would be quite useful to have the ability to be able to receive events or bind to hooks which would allow for data modification before retrieval or write. The scenario would be helpful with data validation when creating/updating records for example or providing a base for webhook functionality eg. call my API when a record is inserted. I am aware that this can partially be achieved via SQL's `sp_invoke_external_rest_endpoint` methods, however it is not universal solution across various data providers.

The events which I think would be useful:
* Before update, create, delete
* After update, create, delete and read

I can imagine this could then be easily extended with custom code, Logic Apps or Functions to execute some custom validation logic, for example, restricting values within a number field.

Also could be useful for autopopulating fields like CreatedOn, ModifiedOn, CreatedBy, ModifiedBy etc.

**Comment by JerryNixon** [comment]
There's a lot of value in this. And a lot of hidden work to do it right.

**Comment by JerryNixon** [comment]
Wait for customer to identify this issue is a priority again. Willing to reconsider.
