### ISSUE TITLE
[Improvement]: Enhance dab CLI tool to check the configuration validity

### ISSUE THREAD

**Issue by kliszaq** [Azure/data-api-builder#1778]
### What happened?

As the development is in progress, the configuration schema changes tend to be quite significant.  I would like to be able to use the dab command tool to check if the current schema is still valid.
As a user I want to validate the schema by using the command
`dab validate`
that would output all the problems with the schema, and if applicable all related configurations (implied by the multi database support) in the current folder.

### Version

0.8.52

### What database are you using?

Azure SQL

### What hosting model are you using?

AppService

### Which API approach are you accessing DAB through?

REST, GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniruddh25** [comment]
hi @kliszaq,

Thank you for your feedback. Does this issue #1579, serve what you need? Please add to its comments if you find anything missing.

Thanks
Aniruddh.

**Comment by kliszaq** [comment]
Indeed, #1579  is what I was asking for.
