### ISSUE TITLE
Investigate and fix use of encoding for after/nextlink

### ISSUE THREAD

**Issue by aaronburtle** [Azure/data-api-builder#1799]
We are currently encoding the nextlink used for pagination using a base64 encode. We need to investigate how client applications are processing this afterlink and confirm if we really need to be encoding this ourselves, or allowing the client application to handle such encodings.

Ultimately, once this information is found, we need to fix the encodings so that the after cursor is opaque with valid base 64 encode.

**Comment by seantleonard** [comment]
The part of the `nextLink` that is encoded is intended to be opaque to the client. Clients should not do anything with the contents of the encoded piece of the nextLink besides provide it to DAB. This allows us to make non-breaking changes to the structure of the encoded bits without the user being affected.

**Comment by seantleonard** [comment]
- Confirm Base64 encoding is URL compatible.

**Comment by Aniruddh25** [comment]
We need to investigate this because the url encoded `nextLink` or `after` clause no longer provides a valid base-64 encoded value. So, the link turns out to not be useful if it contains special characters. This was evident in the OpenAPI response as well.
