### ISSUE TITLE
 [Improvement]: Close the dab process from CLI

### ISSUE THREAD

**Issue by kliszaq** [Azure/data-api-builder#1810]
### What happened?

I am working with a solution that creates the configuration and runs the dab as a separate process.
As the endpoints changes for the production I would like to stop the dab process gracefully with the `CloseMainWindow`. However, the dab process not always wants to stop. Perhaps, there might be an option to stop the host from CLI that is using for example `IHostLifetime` under the hood? Killing the process works perfectly. I would expect that there might be scenarios where safely shutting down the host is expected and it can finish processing of the requests.

### Version

0.8.52

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JerryNixon** [comment]
Wait for customer to identify this issue is a priority again. If this matters to you, we welcome a PR.
