### ISSUE TITLE
[Bug]: Data API Builder is returning HTTP 400 when deployed using Azure Static Web App

### ISSUE THREAD

**Issue by sander1095** [Azure/data-api-builder#1814]
### What happened?

# Bug Description
Hello!

My issue is as follows.
I've created a NextJS 13 SSR app that uses Azure Static Web App together with Azure Data Api Builder with Azure SQL. Everything works fine **locally**.

![image](https://github.com/Azure/data-api-builder/assets/7312681/2c8a4947-0f0d-44fe-ba4c-fc845cf7eb90)

However, when I deploy the app, I get a HTTP 400 error [when deploying](https://github.com/sander1095/polar-dash/actions/runs/6524825195/job/17716866075) and [accessing the data](https://proud-desert-0a06b8303.3.azurestaticapps.net/data-api/rest/TriviaQuestion/):

`{"Message":"{\u0022Message\u0022:\u0022Response status code does not indicate success: 400 (Bad Request).\u0022,\u0022ActivityId\u0022:\u0022b328033d-1f58-4c02-afb9-a61ce9598a75\u0022}","ActivityId":"b328033d-1f58-4c02-afb9-a61ce9598a75"}`

![image](https://github.com/Azure/data-api-builder/assets/7312681/0c7a656c-f1ed-4159-b980-db27208066ab)

I've read [the troubleshooting docs](https://learn.microsoft.com/en-us/azure/data-api-builder/troubleshoot-usage#http-400-bad-request-error) about this but I can't figure it out, because it seems like my Azure SQL and Azure Static Web App resources should have been configured correctly!

If you want more information about my project, take a look [at this PR for the related project](https://github.com/ArcadyRob/polar-dash/pull/41).

# Azure Resource configuration
## Azure SQL
![image](https://github.com/Azure/data-api-builder/assets/7312681/03b80334-4442-4112-89ad-2d9aebb27c43)

## Azure Static Web App
![image](https://github.com/Azure/data-api-builder/assets/7312681/dd66d2f9-1827-463e-b00b-aa27144c5a2d)

## DAB configuration file
```
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.8.52/dab.draft.schema.json",
  "data-source": {
    "database-type": "mssql",
    "connection-string": "@env('DATABASE_CONNECTION_STRING')",
    "options": {
      "set-session-context": false
    }
  },
  "runtime": {
    "rest": {
      "enabled": true,
      "path": "/rest"
    },
    "graphql": {
      "enabled": true,
      "path": "/graphql",
      "allow-introspection": true
    },
    "host": {
      "cors": {
        "origins": [
          "http://localhost:4280",
          "https://proud-desert-0a06b8303.3.azurestaticapps.net/"
        ],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "development"
    }
  },
  "entities": {
    "TriviaQuestion": {
      "source": {
        "object": "dbo.TriviaQuestion",
        "type": "table"
      },
      "graphql": true,
      "rest": true,
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            {
              "action": "read"
            }
          ]
        }
      ]
    }
  }
}
```

# Extra information
Funnily enough, I've had this problem earlier today when I was experimenting with all this [in my "experimental" repo](https://github.com/sander1095/swa-dab-test) and there I got everything to work fine. As far as I can see, I've configured Azure Static Web App + Azure SQL exactly the same way.

### Version

Microsoft.DataApiBuilder 0.8.52+c69925060e1942d28515b9c4b89ea24832da0c7c

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
{"Message":"{\u0022Message\u0022:\u0022Response status code does not indicate success: 400 (Bad Request).\u0022,\u0022ActivityId\u0022:\u0022b328033d-1f58-4c02-afb9-a61ce9598a75\u0022}","ActivityId":"b328033d-1f58-4c02-afb9-a61ce9598a75"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sander1095** [comment]
Hi @seantleonard ! i've tried it multiple times with production mode but it didnt work so I tried to set it to development to get more info about the issue. 

I'll update it back to production just to see if it now magically works again.

**Comment by sander1095** [comment]
Update: Setting it to production doesn't work either.

Proof: https://github.com/sander1095/polar-dash/actions/runs/6536400271/job/17748022010  
Related commit: https://github.com/sander1095/polar-dash/commit/8114d421c39aeaf5f6ecf0bbb55442b4d1929891

**Comment by Aniruddh25** [comment]
FYI : @thomasgauvin

**Comment by sander1095** [comment]
Another update: I have also tried upgrading the SQL database from free tier to a DTU based one, AND i disabled azure network access, saved, and enabled it again and saved again.

Then I tried to deploy again, which also didn't work: https://github.com/sander1095/polar-dash/actions/runs/6536544168/job/17748485515

Next I will try adding my entities to the Azure SQL instance that did work and let my SWA connect to that instead..

**Comment by sander1095** [comment]
Final final update for tonight 😄

I tried removing the db calls and deploy it so the db config file would be running successfully on SWA, even if the calls would be unused. Afterwards I added the DB calls again and deployed, hoping that it would now magically work because of the previous successful release.

This also didn't work.

**Comment by seantleonard** [comment]
Hi @sander1095, 

I'm sorry that my last suggestion did not work for you.

I was able to replicate an HTTP 400 error from Static Web Apps (that I believe may be the root cause of your experienced behavior). As a temporary workaround, can you try the following? This mitigated the issue for me.

In the root of your repo, add a static web apps specific configuration file per [static-web-apps/configuration docs](https://learn.microsoft.com/azure/static-web-apps/configuration): `staticwebapp.config.json`.:

```json
{
    "routes": [
        {
            "route": "/data-api/*",
            "allowedRoles": [
                "anonymous",
                "authenticated"
            ]
        }
    ]
}
```
The above snippet shows a routing rule that explicitly defines which roles are allowed to access DAB using the database connections feature in SWA. 

The `allowedRoles` property should reflect any roles you have defined in your DAB runtime config. Setting these roles will allow any requests with access tokens denoting the referenced roles to be passed from SWA to DAB. DAB will then continue to validate the token and perform authorization based on token contents and your DAB runtime config.

While this worked in my environment, I would appreciate @thomasgauvin 's input about whether this is actually required, and if so, if it can be documented in SWA docs.

**Comment by sander1095** [comment]
Hi @seantleonard .

I've tried this, and it [did not work](https://github.com/sander1095/polar-dash/actions/runs/6557216241). 

Could you look at the state of my repo in [the commit](https://github.com/sander1095/polar-dash/commit/fff81857da99633be9ecad16a71abd368d9df63e) where I added the `staticwebapp.config.json`? I'm curious to see the differences..

[The documentation](https://learn.microsoft.com/en-us/azure/static-web-apps/deploy-nextjs-hybrid#unsupported-features-in-preview) says that `staticwebapp.config.json` is not supported for next.js SSR, which is what my project uses:

> * The staticwebapp.config.json file.
>   * Features such as custom headers and routing can be controlled using the next.config.js file.

I don't know how to configure this in `next.config.js`, because those roles you defined in `staticwebapp.config.json` seem to be a SWA thing, not a `nextjs` thing.

**Comment by sander1095** [comment]
I've also tried to [change the auth to anonymous](https://github.com/sander1095/polar-dash/commit/4c72416c9acd51915e5630aec9f1bd81fdf5791c) but that also [did not work](https://github.com/sander1095/polar-dash/actions/runs/6557326462).

In one of my previous comments I said that I had another project where everything worked. I copied all the SWA + Db config from that project into this one, and it did not have an effect. So I'm not sure how a SWA config file would now help :)

**Comment by sander1095** [comment]
I have figured out the root cause (With help ;-)).

The problem was a simple case of incorrect SQL credentials whilst linking the database. I never thought about this because I think it would be logical that database linking can only succeed when SQL credentials are correct. This, apparently, is not the case.

If that would have been the case, this entire issue could have been avoided. I have mentioned this in a seperate SWA issue here: https://github.com/Azure/static-web-apps/issues/1299.

I would suggest updating the troubleshooting AND tutorial documentation so people ensure their credentials are correct until (hopefully) Azure will just check these itself.

Thanks for your help everyone!
