### ISSUE TITLE
Add support for sending logs to a text file

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1818]
### Discussed in https://github.com/Azure/data-api-builder/discussions/1812

<div type='discussions-op-text'>

<sup>Originally posted by **meareal** October 13, 2023</sup>
In `development` mode, we get logs in the console. Ideally we would be able to log every request and response to a text file we specify in dab-config.json file.

In the past, I have added a middleware component to our custom Web APIs to log every request and every response in the `InvokeAsync` method.</div>

**Comment by JerryNixon** [comment]
Reference #2371
