### ISSUE TITLE
[Bug]: CLI link is unusable

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1819]
### What happened?

A bug happened!

![image](https://github.com/Azure/data-api-builder/assets/1749983/795f6cb7-f70d-497c-9e4a-c7516fbea476)

The link to the docs in `--LogLevel` is unusable because it has a large & invalid space. 

I think this may be trying to fix a wrapping issue, but the querystring is not an important part. 

You can just use `https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel`

### Version

0.8.52+c69925060e1942d28515b9c4b89ea24832da0c7c

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST, GraphQL

### Relevant log output

```Text
C:\Users\jerry>dab start --help
Microsoft.DataApiBuilder 0.8.52+c69925060e1942d28515b9c4b89ea24832da0c7c
c Microsoft Corporation. All rights reserved.

  --verbose              Specify logging level as informational.

  --LogLevel             Specify logging level as provided value, see:
                         https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.loglevel?view=dotnet-                         plat-ext-7.0

  --no-https-redirect    Disables automatic https redirects.

  -c, --config           Path to config file. Defaults to 'dab-config.json' unless 'dab-config.<DAB_ENVIRONMENT>.json'
                         exists, where DAB_ENVIRONMENT is an environment variable.

  --help                 Display this help screen.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
need a fw link.

**Comment by seantleonard** [comment]
Updating to the link: https://go.microsoft.com/fwlink/?linkid=2263106

Looks like:
![image](https://github.com/Azure/data-api-builder/assets/6414189/95ca056c-eb6a-47bf-b083-98d725c8666b)
