### ISSUE TITLE
Database Query Generation Design Doc - Nested Inserts

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#1887]
Write and check-in a design doc for the query generation part of Nested Inserts functionality

**Comment by seantleonard** [comment]
Depends on design finalization and answered questions for schema generation  (update this text if necessary)

**Comment by seantleonard** [comment]
- currently adding logic for building input types

**Comment by seantleonard** [comment]
Schedule design discussion before .11 close.

**Comment by severussundar** [comment]
Current Status:

- End to End flow is working fine
![image](https://github.com/Azure/data-api-builder/assets/11196553/71ca6626-eec8-4c08-a430-dd7b18c7344c)

**Book Table**

![image](https://github.com/Azure/data-api-builder/assets/11196553/5ee93cad-9bff-4a39-b25b-da0fc4524d8d)

 
**Publisher Table**
![image](https://github.com/Azure/data-api-builder/assets/11196553/46ef801f-7ff1-4891-a905-175531efa4dd)

**Authors Table**
![image](https://github.com/Azure/data-api-builder/assets/11196553/1e7daf01-d719-46aa-8d20-005d8b235f9a)

**Book Author Link Table**
![image](https://github.com/Azure/data-api-builder/assets/11196553/25bcbaea-3159-44b0-97c6-5117241dbbac)

**Reviews Table**
![image](https://github.com/Azure/data-api-builder/assets/11196553/75c5fcff-4d67-49ea-bd83-df9906d112a6)

**Comment by severussundar** [comment]
Scenarios Completed: 
1. Point mutation operation ~ `createbook`
2. Multiple mutation operation ~ `createbooks`


For both of these operations, the below aspects of the feature are completed.

1. Successful database query generation involving nested entities varying depths.
      - All relationship types are completed: 1:1, 1: N, N:1, M: N (including linking table insertion)
3. Transactional aspect of the feature - Successful rollback of all created items when there is any failure
4. Mappings - When the column name is exposed through a different name for graphQL operations
5. PK being Auto-generated vs Non-Auto generated (at any level)
6. Selection set resolution 
       - Aspects like pagination: `nextCursor`, `hasNext` fields etc. are also completed
7. Incorporating database policies when defined
       - `create` policy: Successfully incorporated during the creation of a new record. When any of the insert fails due to database policy, all the inserts for the whole nested insert operation are rolled back successfully.
       - `read` policy: Successfully incorporated during the selection set resolution phase. When a record does not satisfy the read database policy defined, it will not be returned in the response.
 
 Things pending:

     1. Scenarios where the relationship is defined only at the config file level (no FK constraints defined)
     2. Handling the scenario where relationship is defined at both the config level and database level - Need to write logic throw appropriate errors.

**Comment by seantleonard** [comment]
@severussundar Do the pending items have to implemented in the same changeset? can they be a part of follow up PRs?

**Comment by severussundar** [comment]
Hey Sean, they will in a separate PR.
