### ISSUE TITLE
GraphQL Mutation Request Validations - Nested Inserts

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#1889]
Perform validations on the GraphQL mutation requests to ensure that it is valid.
```[tasklist]
### Tasks
```

**Comment by seantleonard** [comment]
Dependent on #1887

**Comment by seantleonard** [comment]
no longer dependent.

**Comment by seantleonard** [comment]
- logic for when relationship defined in config
- when defined in db.

**Comment by ayush3797** [comment]
> * logic for when relationship defined in config
> * when defined in db.

Opened an issue to explain/track this: https://github.com/Azure/data-api-builder/issues/2018

**Comment by ayush3797** [comment]
Currently status for this: listing all the invalid request cases that can arise.
