### ISSUE TITLE
DAB Feature Availability Matrix for Azure Databases

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#1920]
Add documentation listing out which DAB features are available for each supported Database type.

**Comment by seantleonard** [comment]
CosmosDB column need to be either `no` or `-` for REST and Caching.

Also GraphQL mutations for relationships is not yet supported for any database. That's in development.

**Comment by abhishekkumams** [comment]
Application Insights is independent of Database used, So its available for all.

**Comment by sajeetharan** [comment]
Cosmos DB Column should be renamed as Cosmos DB (NOSQL API) - somewhere need to indicate it is for NOSQL API only..

**Comment by seantleonard** [comment]
I updated the REST section to show `-` for Cosmos with an annotation describing why.

Also updated cosmos header per Sajee's suggestion to `CosmosDB for NoSQL`

**Comment by APortolesScope** [comment]
Does the new DB type DWSQL must appear here?
https://github.com/Azure/data-api-builder/pull/1873

**Comment by seantleonard** [comment]
`Column/Property Mapping/Rename` under Other Features needs to be more granular: not supported with stored procedures.

Updates I already made:
- `Column/Property Mapping/Rename` -> not supported with CosmosDB_NoSql
- Managed Identities -> Clarified to "System Assigned Managed Identities (Entra ID/ Azure AD)" because user assigned managed identities are not supported out of box. SWA db connections has a layer on top of dab that adds support for user assigned MI's, but not the stand-alone dab engine.

**Comment by seantleonard** [comment]
Updated for 1.1.7:
-  In-Memory Cache -> CosmosDB (Yes)
- `application_name` -> PostgreSql (Yes)

**Comment by seesharprun** [comment]
This will be published later today. We can edit the article in-place after publishing.

#please-close

**Comment by seesharprun** [comment]
<https://learn.microsoft.com/azure/data-api-builder/feature-availability>

**Comment by JerryNixon** [comment]
Added to docs here: https://learn.microsoft.com/en-us/azure/data-api-builder/feature-availability
