### ISSUE TITLE
[Bug]: Can't disable REST for just one Table

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1924]
### What happened?

`dab add "Series_Character" --source "[dbo].[Series_Character]" --source.type "Table" --source.key-fields "CharacterId,SeriesId" --rest "false" --graphql "false"`

This effectively disables `graphql` for this table.

This does not disable `rest` for this table.

There is no CLI command enabling this important capability. Why? Because this table is a cross reference table for a many-to-many relationship that should not be exposed in Swagger - or at least the developer should have the option to hide it. 

### Version

Microsoft.DataApiBuilder 0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by severussundar** [comment]
Hey @JerryNixon, I tried to repro this. REST APIs are successfully getting disabled for the entity.

Command: `dab add Book_Author_Link  -c "dab-config.MsSql.json" --source "book_author_link" --rest false --graphql false --permissions "anonymous:*"`


```https
GET  /api/Book_Author_Link
```

![image](https://github.com/Azure/data-api-builder/assets/11196553/fd9a5828-cedc-48a4-9923-0a3554fefbf6)

**Comment by abhishekkumams** [comment]
@JerryNixon , Let's close this issue if it's giving expected results?
