### ISSUE TITLE
Multiple relationships between same source and target entities

### ISSUE THREAD

**Issue by ayush3797** [Azure/data-api-builder#1930]
Currently, we allow defining multiple relationships between the same source and target entities. A user is allowed to define multiple relationships each with different source fields/target fields and even different cardinalities. This is not only logically incorrect but also difficult to make sense out of. Hence, we need to add a validation to ensure that multiple relationships between same source and target entities are not allowed.

This is currently also a bug. Assume in a config file you have defined 2 relationships from books to publishers:

<img width="247" alt="image" src="https://github.com/Azure/data-api-builder/assets/34566234/a2816368-c934-44e7-8cc8-e4035946544b">

And then you will get an exception when you do a query like:
<img width="846" alt="image" src="https://github.com/Azure/data-api-builder/assets/34566234/f00a0568-3678-46e7-86d6-3cc237827a7e">

This is because even though DAB allows users to define multiple relationships, it does not honor a relationship uniquely but does a union of source and target fields across all the relationships for the (source,target) pair. This is evident from the generated query:

```tsql
SELECT TOP 100 [table0].[id] AS [id], JSON_QUERY ([table1_subq].[data]) AS [publishers] FROM [dbo].[books] AS [table0] OUTER APPLY (SELECT TOP 1 [table1].[id] AS [id], [table1].[name] AS [name] FROM [dbo].[publishers] AS [table1] 
WHERE 
[table0].[publisher_id] = [table1].[id] AND 
[table0].[title] = [table1].[name] AND 
[table1].[name] = [table0].[title] 
ORDER BY [table1].[id] ASC FOR JSON PATH, INCLUDE_NULL_VALUES,WITHOUT_ARRAY_WRAPPER) AS [table1_subq]([data]) WHERE 1 = 1 ORDER BY [table0].[id] ASC FOR JSON PATH, INCLUDE_NULL_VALUES
```
**Note:** The duplicate WHERE clause (`[table0].[title] = [table1].[name] AND [table1].[name] = [table0].[title]`) that you see is a result of an existing known bug (see [here](https://github.com/Azure/data-api-builder/issues/1948))

So, even though we queried `publishers`, we can see that the JOIN also included the source/target fields from the relationship `pub` in the WHERE clause - `[table0].[title] = [table1].[name]`. Ideally, we should have only be joining based on - `[table0].[publisher_id] = [table1].[id]`. 

This I think is also something happening in: https://github.com/Azure/data-api-builder/issues/1940

**Comment by seantleonard** [comment]
While we can't predict what kind of database designs (table/entity/relationships) DAB processes, we can still come up with some (arguably) valid schemas. While this is an arbitrary example, a car manufacturer/dealer may have multiple fields that may make use of values from another table. For example, color. A car typically has one color on the exterior and a different color on the interior: exterior red, interior tan. That would result in two fields in the car table pointing to the color table. That would require us to allow two relationships to be defined between a source and target table. In this case the cardinalities are the same.

```mermaid
erDiagram
    CAR ||--|| COLOR : "interior_color"
    CAR ||..|| COLOR : "exterior_color"
    CAR {
        int id
        int make
        int interior_color
        int exterior_color
    }
    COLOR {
        int id
        string color_name
    }
```

**Comment by seantleonard** [comment]
```tsql
SELECT [cars].[id]
      ,[make]
      ,[model]
      ,[color1].[color_name] AS exterior_color
	  ,[color2].[color_name] AS interior_color
  FROM [dabdev].[dbo].[cars]
LEFT OUTER JOIN [colors] AS [color1] on [cars].[interior_color] = [color1].[id] 
LEFT OUTER JOIN [colors] AS [color2] on [cars].[exterior_color] = [color2].[id]
```

would result in:

|id	|make|	model|	exterior_color|	interior_color|
|-|-|-|-|-|
|2	|Hyundai|	1|	Red|	White|
|3	|Ferrari	|2	|Red	|Tan|

**Comment by severussundar** [comment]
Hey Sean, this scenario can be handled using a single relationship.

In a single relationship, 
 a) Users can configure multiple relationship fields (source.fields and target.fields) 
 b) DAB can successfully infer multiple columns used in the FK constraints.

So, when both pairs of relationship fields are a) either specified in the config b) used in the FK constraint, would result in the DAB generating the same database query you have mentioned.

**Comment by ayush3797** [comment]
Keeping it in 0.12rc for now. Might push back to 1.1 later.

**Comment by evan-buss** [comment]
> Hey Sean, this scenario can be handled using a single relationship.
> 
> In a single relationship, a) Users can configure multiple relationship fields (source.fields and target.fields) b) DAB can successfully infer multiple columns used in the FK constraints.
> 
> So, when both pairs of relationship fields are a) either specified in the config b) used in the FK constraint, would result in the DAB generating the same database query you have mentioned.

Can you provide an example of this? I can't seem to get this working. I have a table with an `EditorId` and an `AuthorId` that references a record in the `Users` table by `Id`. Here is my relationship definition:

```json
 "Author": {
    "cardinality": "one",
    "target.entity": "User",
    "source.fields": [ "AuthorId" ],
    "target.fields": [ "Id" ]
  },
  "Editor": {
    "cardinality": "one",
    "target.entity": "User",
    "source.fields": [ "EditorId" ],
    "target.fields": [ "Id" ]
  }
```

The GraphQL schema seems to be correct in that I can write a query to get details of the User, but the response is always `null`.

Looking at the relevant subquery:

```sql
SELECT TOP 1 [table6].[Title] AS [Title]
FROM [dbo].[Users] AS [table6]
WHERE [table0].[AuthorId] = [table6].[Id]
	AND [table6].[Id] = [table0].[AuthorId]
	AND [table0].[EditorId] = [table6].[Id]
	AND [table6].[Id] = [table0].[EditorId]
ORDER BY [table6].[Id] ASC
FOR JSON PATH
	,INCLUDE_NULL_VALUES
	,WITHOUT_ARRAY_WRAPPER
) AS [table6_subq]([data])
```

For some reason it's adding a `WHERE` condition for both the `EditorId` and the `AuthorId`.
