### ISSUE TITLE
[Bug]: $after querystring parameter gets added multiple times

### ISSUE THREAD

**Issue by cdgipson** [Azure/data-api-builder#1932]
### What happened?

Ran the initial request with ?$first=5.  

http://localhost:5000/api/StaffType?$first=5

Then ran the next link, it only contained one $first and one $after.  

http://localhost:5000/api/StaffType?$first=5&$after=W3siRW50aXR5TmFtZSI6IlN0YWZmVHlwZSIsIkZpZWxkTmFtZSI6IklkIiwiRmllbGRWYWx1ZSI6OSwiRGlyZWN0aW9uIjowfV0=

The following nextLink contained two $after parameters. 

http://localhost:5000/api/StaffType?$first=5&$after=W3siRW50aXR5TmFtZSI6IlN0YWZmVHlwZSIsIkZpZWxkTmFtZSI6IklkIiwiRmllbGRWYWx1ZSI6OSwiRGlyZWN0aW9uIjowfV0%3D&$after=W3siRW50aXR5TmFtZSI6IlN0YWZmVHlwZSIsIkZpZWxkTmFtZSI6IklkIiwiRmllbGRWYWx1ZSI6MTcsIkRpcmVjdGlvbiI6MH1d

When you follow that link it results in the following error.

{
  "error": {
    "code": "BadRequest",
    "message": "The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.\n   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)\n   at System.Convert.FromBase64String(String s)\n   at Azure.DataApiBuilder.Core.Resolvers.SqlPaginationUtil.Base64Decode(String base64EncodedData) in /src/src/Core/Resolvers/SqlPaginationUtil.cs:line 516\n   at Azure.DataApiBuilder.Core.Resolvers.SqlPaginationUtil.ParseAfterFromJsonString(String afterJsonString, PaginationMetadata paginationMetadata, ISqlMetadataProvider sqlMetadataProvider, String entityName, RuntimeConfigProvider runtimeConfigProvider) in /src/src/Core/Resolvers/SqlPaginationUtil.cs:line 285",
    "status": 400
  }
}`
`

I expected the endpoint to return the nextLink only containing one $after parameter, which points to the next set of records based upon the request that generated the response.

### Version

0.8.52

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cdgipson** [comment]
I evaluated the contents of the two $after parameters.  This makes a slight bit of sense to contain info for the current set of data and the next. However, it is still up to the calling application to store previous $after values so that it can page the data in both directions.  If we are taking the assumption that the calling app will be doing this, I feel that only the $after data parameter for the next set of records needs to be returned.

**Comment by severussundar** [comment]
Hey @cdgipson, I'm unable to repro this. In my setup, the `nextLink` always contains only one `$after` field (Using the `nextLink` twice does not lead to the addition of 2 `$after` fields in the URL.). Also, using the `nextLink`, I'm able to successfully query until the end of records contained in the entity without hitting any errors. I tried this against table, view and stored procedure;  everything seems to work correctly.

Ex: 
```http
GET  /api/Book?$first=2
```

First nextLink ---> `https://localhost:5001/api/Book?$first=2&$after=W3siVmFsdWUiOjQsIkRpcmVjdGlvbiI6MCwiVGFibGVTY2hlbWEiOiJkYm8iLCJUYWJsZU5hbWUiOiJib29rcyIsIkNvbHVtbk5hbWUiOiJpZCJ9XQ%3D%3D`

Second nextLink ---> `https://localhost:5001/api/Book?$first=2&$after=W3siVmFsdWUiOjYsIkRpcmVjdGlvbiI6MCwiVGFibGVTY2hlbWEiOiJkYm8iLCJUYWJsZU5hbWUiOiJib29rcyIsIkNvbHVtbk5hbWUiOiJpZCJ9XQ%3D%3D`


One thing to note is that the `nextLink` generated is a complete URL against which the subsequent GET request can be executed directly (No modifications are needed).

Could you please share more info regarding your setup that leads to this error - your config file, the type of entity, the way you are executing the GET requests, etc.

**Comment by seantleonard** [comment]
Fixed with #2006 in latest stable release. `0.10.23` https://github.com/Azure/data-api-builder/releases/tag/v0.10.23
