### ISSUE TITLE
[Bug]: Database queries inside Azure SWA yield "InternalServerError" 

### ISSUE THREAD

**Issue by zebleck** [Azure/data-api-builder#1934]
### What happened?

I get the error `{"Message":"InternalServerError","ActivityId":"<some-id>"}` on every GraphQL request inside my Azure Static Web App that has a connection to our database.

1. Connected a database to our Azure Static Web App using the Azure portal.
2. Every GraphQL query returns something along the lines of: {"Message":"InternalServerError","ActivityId":"781044af-27f1-49ef-a77f-c1ae5656f72e"}
3. Locally it works if we run a command like swa start ./src --swa-config-location config/local --data-api-location swa-db-connections/ --api-location api/ --run \"npm run start\"
4. The code we use is synchronized with the production SWA using Github Actions (the integration was selected in the portal when setting up the SWA).

One annoying thing is, it just worked a few hours ago. However, I didn't change the configuration of the SWA, database or its connection.

Also, I don't know if this is related but if I change the "mode" from "production" to "development" inside the swa-db config, it now doesn't work even locally, yielding the following error:

```
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]       Unable to complete runtime initialization. Refer to exception for error details.
[dataApi]       System.InvalidCastException: Unable to cast object of type 'Azure.DataApiBuilder.Config.DatabasePrimitives.DatabaseView' to type 'Azure.DataApiBuilder.Config.DatabasePrimitives.DatabaseTable'.
[dataApi]          at Azure.DataApiBuilder.Core.Configurations.RuntimeConfigValidator.ValidateRelationshipsInConfig(RuntimeConfig runtimeConfig, ISqlMetadataProvider sqlMetadataProvider) in /_/src/Core/Configurations/RuntimeConfigValidator.cs:line 632
[dataApi]          at Azure.DataApiBuilder.Service.Startup.PerformOnConfigChangeAsync(IApplicationBuilder app) in /_/src/Service/Startup.cs:line 682
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]       Could not initialize the engine with the runtime config file: staticwebapp.database.config.json
```

### Version

0.9.7

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
{"Message":"InternalServerError","ActivityId":"781044af-27f1-49ef-a77f-c1ae5656f72e"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rthadr** [comment]
Same for me on REST

**Comment by rthadr** [comment]
@zebleck not sure if you have solved this, but for me it was related to #1956. When, I hardcoded my connection string into the staticwebapp.database.config.json file, and re-deployed it started working again.

**Comment by sqlgreen** [comment]
I think the original issue was due to an outage of the SWA hosted version of data-api, we had the same issue. As per the OP, "it just worked a few hours ago"... "I didn't change the configuration of the SWA". 

In the same timeframe we had a deployed app, stable and working correctly for weeks, stops working, no changes. 
Raised an incident, there was an issue rectified by the team.

There are other causes for InternalServerError on SWA, but the specific scenario described above is hopefully not something we will see again :)

**Comment by zebleck** [comment]
ok will close this
