### ISSUE TITLE
Validations required for source/target fields in relationships

### ISSUE THREAD

**Issue by ayush3797** [Azure/data-api-builder#1935]
Consider these scenarios for source/target fields defined for a relationship:

1. `SourceFields`: **NULL**, TargetFields: **Non-NULL** (and vice-versa)
2. `SourceFields.size() ! = TargetFields.size()`
3. `SourceFields`/`TargetFields` contains one or more fields/columns which do not belong to the source/target entities respectively.

All these scenarios should be caught during validation.

**Comment by severussundar** [comment]
Validations can be added to check that each source, target field specified is a valid column in the underlying database object.
