### ISSUE TITLE
[Bug]: DAB initialization fails in SWA when stored procedure is added to the config

### ISSUE THREAD

**Issue by tdutch1** [Azure/data-api-builder#1947]
### What happened?

After ruunning the following DAB CLI command and starting the dab runtime locally, the "VehiclePrograms" API returns data from the Azure SQL stored procedure as expected.

dab add VehiclePrograms --config "dab-config.json" --source dbo.usp_GetVehicleProgramsByVin --source.type "stored-procedure" --source.params "CallerId:X,Vin:X" --permissions "anonymous:execute" --rest.methods "get" --graphql false

After deploying the new configuration to a Static Web App, all APIs fail and return "400 Bad Request". After removing the new stored procedure definition from "entities" in the config, all original APIs start working again.

The database connection in the SWA is currently using a database owner account (SQL auth), so this problem is not likely related to a permission issue.

### Version

0.9.7

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tdutch1** [comment]
The problematic Azure SQL stored procedure has SELECT statements within an IF/ELSE block. I tested with a simple stored procedure that has only a SELECT statement (and no parameters) and it worked when running locally and in the SWA. So, the problem might be with the use of parameters and/or with having SELECT statements within IF/ELSE, which might cause the SWA-based DAB runtime to fail when getting the stored procedure metadata.

Here's a simplified version of the stored procedure that's failing when running in the SWA:

CREATE PROCEDURE dbo.usp_GetVehicleProgramsByVin
(
    @CallerId VARCHAR(50),
    @Vin VARCHAR(17)
)
AS
BEGIN
    SET NOCOUNT ON;

    IF @CallerId = 'A'
    BEGIN
        SELECT VEHICLE_PROGRAM_CODE FROM [dbo].[PROGRAM_VEHICLE] WHERE FULL_VIN = @Vin;
    END
    ELSE IF @CallerId = 'B'
    BEGIN
        SELECT VEHICLE_PROGRAM_CODE FROM [dbo].[PROGRAM_VEHICLE] WHERE FULL_VIN = @Vin AND [STATUS] = 'Closed';
    END
    ELSE
    BEGIN
        SELECT 'Invalid CallerId';
    END
END

**Comment by severussundar** [comment]
Hey @tdutch1, thank you for bringing this up. 

There are some limitations in the types of stored procedures that are supported by Data API builder. Please find the [documentation](https://learn.microsoft.com/en-us/azure/data-api-builder/views-and-stored-procedures#stored-procedures)
around the same.

Having said that, I am able to successfully execute REST requests against a similar stored procedure (one with SELECT statements with conditional statements).  


For GET requests, the parameters for the stored procedures have to passed through the URL 

```https
GET /api/<sp_entity_name>?CallerId="..."&Vin="..."
```

But with POST, PUT and PATCH requests, the parameters have to passed through the request body as a JSON.

Something like this,
```json
{
   "CallerId": "...",
   "Vin": "..."
}
```

**Comment by tdutch1** [comment]
Hi @severussundar, thank you for the documentation link. The main issue, though, is that DAB running locally (i.e., dab start CLI) was able to validate and use the stored procedure configuration settings and return data from the stored procedure but DAB running in a Static Web App (SWA) in Azure failed during validation/initialization. 

My guess is that the SQL library that DAB uses to identify the structure of the data returned by the stored procedure is different between local and hosted (SWA). If that's the issue, then there will need to be a way to make sure DAB's initialization is identical across implementations. Otherwise, with no visibility into specific initialization errors (i.e., no output when hosted by SWA), there will be no way to troubleshoot problems like this.

**Comment by abhishekkumams** [comment]
@tdutch1, when using the dab v0.8.52 locally and do you also see the differences between local and hosted(SWA)?

**Comment by tdutch1** [comment]
@abhishekkumams How can I be sure that I'm running the same DAB version locally that the SWA is running? I'm finding other differences between the latest build (running locally) and what the SWA hosted DAB is providing. I know that everything is in Beta/preview at this point, but I'm hoping to be able to determine how to run the same DAB version locally that the SWA is hosting.

**Comment by abhishekkumams** [comment]
Currently, SWA is running v0.9.7. Application Insights is not supported in SWA yet.

**Comment by seantleonard** [comment]
Hi @tdutch1,

Thank you for your patience. To match SWA Database Connections DAB usage, use 0.9.7 locally. https://github.com/Azure/data-api-builder/releases/tag/v0.9.7

Without correlationIds returned in your SWA DB Connections errors, I can't be 100% certain this is your issue, though here is what I needed to do to get my own sample working with the information you provided:

1. Grant execute permissions on stored procedure to db user used to connect to database
2. Add `parameters` section with default values to dab config

## SQL User permissions :
The issue seems to be with permissions granted to the SQL account used by DAB. Is the account you use for SWA DB Connections versus local testing different? In my case, my local account is a member of the `db_owner` role so none of these startup errors were occurring. 

In my SWA environment, I had configured a system assigned managed identity. That identity needed to be granted the following permission on my stored procedure to allow DAB to startup correctly:
```tsql
GRANT EXECUTE ON OBJECT::databasename.dbo.usp_GetVehicleProgramsByVin
    TO <database_user>
```

Database users only assigned the sql roles `db_datawriter` and `db_datareader` don't possess the sufficient permissions when using store procedures.

## Dab config `parameters`

Additionally, I needed to explicitly define default values for the parameters in my `dab-config.json`:
```json
      "SpTest": {
        "source": {
          "object": "dbo.usp_GetVehicleProgramsByVin",
          "type": "stored-procedure",
          "parameters": {
            "CallerId": "1",
            "Vin":  "1"
          }
        },
        "permissions": [{"role":"authenticated", "actions": ["*"]}]
      }
```

**Comment by seantleonard** [comment]
Hi @tdutch1 just checking in. Were you able to resolve the stored procedure issue you were encountering with SWA.

**Comment by seantleonard** [comment]
Glad it works for you now!

And yes, I agree with the following and we're evaluating the best solution to achieve this.
>  Ideally, if it "runs on my machine", it will run in SWA
