### ISSUE TITLE
Add support for enabling nested mutation from CLI

### ISSUE THREAD

**Issue by ayush3797** [Azure/data-api-builder#1950]
This issue tracks the efforts needed for exposing the feature flag options through CLI commands and subsequently, serializing the same in the config file.

**Comment by severussundar** [comment]
Proposal:

Property Name: `nested-inserts-enabled`
Position in the config file: This will be a property within `runtime.graphql`. Placing the element here implies that when the field is set to true/false, the nested inserts feature is enabled/disabled for all the entities.

One more thing to note: When the property is updated to `true`/`false` to enable/disable the feature, the engine will have to be restarted for the change to take effect. 

In the first iteration, hot reloading of this flag will not be supported. This can be added iteratively in the subsequent versions (if needed).
  
@JerryNixon @Aniruddh25 @seantleonard @ayush3797 Please kindly share your thoughts.

**Comment by ayush3797** [comment]
In future, we might also add support for nested updates. Having a feature directly in the config for nested inserts won't scale well. Instead, we should add an object (something like `nested-mutations`) and then inside that object we can have objects storing properties for inserts/updates.

Also we should be creating objects for inserts/updates because we don't know what all inputs we might need from the user. In future, we might also allow them to specify the nesting limit (due to obvious payload size considerations). Then such a property can also go in the already existing json object. This is just one use case I can think of right now but more can come up as we move forward.

```json
"nested-mutations":{
    "inserts":{
        "enabled": true,
        "nesting-limit": 10
    },
    "updates":{
        "enabled": false,
        "nesting-limit": 10
    },
}
```

**Comment by JerryNixon** [comment]
Would this also be a possibility to reduce syntax?

````JSON
"nested-mutations":{
    "*":{
        "enabled": true,
        "nesting-limit": 10
    },
    "inserts":{
        "enabled": true,
        "nesting-limit": 10
    },
    "updates":{
        "enabled": false,
        "nesting-limit": 10
    },
}
````

**Comment by severussundar** [comment]
Yes, `*`   would help eliminate redundant entries when the same settings are to be applied for all the operations. 

I am inclined to start off with just the `insert` section. The reason being that, nested update operation is still under evaluation. 
When adding the support for `update` operation, the logic for interpreting `*` as `insert + update` can be introduced.   

Adding it now is pre-mature for the following reasons:
1) `*` would expand to only `insert`
2) When adding support for `update`, a logic change would definitely be required in both CLI and engine to interpret `*` to be `insert, update`. So, we can introduce `*` when implementing the `update` operation.

**Comment by JerryNixon** [comment]
100% agree.

**Comment by severussundar** [comment]
CLI Option in the init command: `--graphql.nested-insert.enabled`. This would be an optional field.

Sample commands:

1. `dab init --database-type mssql --connection-string connString --graphql.nested-insert.enabled true`
2. `dab init --database-type mssql --connection-string connString --graphql.nested-insert.enabled false`

**Comment by JerryNixon** [comment]
Thanks for keeping the CLI in sync. Looks great.

**Comment by severussundar** [comment]
Based on inputs in the review comments, `nested-insert` was renamed to `nested-create`.

CLI Option: `--graphql.nested-create.enabled` 

JSON property

```json
     "runtime":{
      ...
       "graphql": {
           ...
           "nested-mutations": {
               "create": {
                     "enabled": true/false
                }
           }
       } 
     }
```

Further the feature (and consequentially, the CLI option name and JSON properties) is going to be renamed since `nested-mutations` has a different meaning (details in the graphql specs https://github.com/graphql/graphql-spec/issues/252 ). 

The renaming of the feature, CLI option, fields in the config files are tracked under the issue: [#2090 ](https://github.com/Azure/data-api-builder/issues/2090)

**Comment by severussundar** [comment]
Closing this issue as PR https://github.com/Azure/data-api-builder/pull/1983 is merged.
