### ISSUE TITLE
Separate engine workflow depending on whether nested mutations are on/off

### ISSUE THREAD

**Issue by ayush3797** [Azure/data-api-builder#1951]
The purpose of the issue is to track the efforts needed for 
 a) Consuming the feature flag fields in the config file 
 b) Adding different code paths in the engine based on whether the feature flag is enabled or disabled

**Comment by JerryNixon** [comment]
The content of this issue has no grammatical errors! ;)

![image](https://github.com/Azure/data-api-builder/assets/1749983/54fa387c-8c26-49d1-9771-c8509224ea70)

**Comment by JerryNixon** [comment]
The reasoning around this issue includes giving the ability for developers to avoid any startup cost associated with nested mutations. Developers can already change read/write permissions of entities which can effectively disable mutations. The nuance here is that disabling them globally can mean the engine doesn't have to compute the schema at startup. Please refer to #1950

**Comment by severussundar** [comment]
> The reasoning around this issue includes giving the ability for developers to avoid any startup cost associated with nested mutations. Developers can already change read/write permissions of entities which can effectively disable mutations. The nuance here is that disabling them globally can mean the engine doesn't have to compute the schema at startup. Please refer to #1950

Thank you for adding this. Updated the description.

When the feature is disabled, the schema will be generated the way it is right now; thus avoiding additional computations, memory utilized etc.

**Comment by seantleonard** [comment]
Follows up the work from #1950
