### ISSUE TITLE
[Bug]: Unable to use the generated eq filters on string or ID fields in graphql

### ISSUE THREAD

**Issue by pingu2k4** [Azure/data-api-builder#1953]
### What happened?

Hey.
We are using DAB with cosmos DB. Any time that we attempt to filter a string or ID field by a given value, where said value is also the partition key, we get no data returned.

Let me provide a minimal example...
We have a Roles container, containing simple roles with an id, tenandId, roleName. Currently, all items have the tenantId of `9cbe5961-7060-479f-a4f4-fd4cb03d6550`, but of course this won't always be the case.

If we run the following query, everything works as expected and we get our data out:

```graphql
query Roles {
    roles(filter: { tenantId: { eq: "9cbe5961-7060-479f-a4f4-fd4cb03d6550" } }) {
        items {
            id
            tenantId
            roleName
        }
    }
}
```

The problem arises where we attempt to parameterise the filter value. Using the following query, and variables gets us no data:
```graphql
query Roles($tenantId: ID!) {
    roles(filter: { tenantId: { eq: $tenantId } }) {
        items {
            id
            tenantId
            roleName
        }
    }
}
```
```json
{
    "tenantId": "9cbe5961-7060-479f-a4f4-fd4cb03d6550"
}
```

With the parameterised query, if we change the filter from `eq` to `neq`, then we still get no data but this is correct behaviour of course. However when we then change the tenantId in the variables json, keeping the filter to a `neq` filter... we then get all the data out. So, the `neq` behaves correctly when parameterised, however in all instances, where the field we are filtering is the partition key, is a string or ID, and we are using the `eq` filter - we will get no data back 100% of the time.

For clarity, when I say that we get no data back, we do get a response but the items are empty, which isn't expected. There are no errors returned or anything. Example response:
```json
{
    "data": {
        "roles": {
            "items": []
        }
    }
}
```

### Version

0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Local (including CLI)
Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhishekkumams** [comment]
when running locally using v0.9.7 and 0.10.11-rc, i was able to fetch the data using both `eq` and `neq` for sql as well cosmosDB.
![image](https://github.com/Azure/data-api-builder/assets/102276754/e35283ec-8039-4e5f-a5bf-ce4e6f4da78a)

**Comment by neeraj-sharma2592** [comment]
@pingu2k4 , I able to reproduce the issue. We are looking into this issue. Meanwhile could you also share the error you are getting? or you are just getting an empty response?

**Comment by pingu2k4** [comment]
> @pingu2k4 , I am able to reproduce the issue. We are looking into this issue. Meanwhile could you also share the error you are getting? or you are just getting an empty response?

Hey, thanks for looking into it.

I get no error at all, just empty data being returned.

**Comment by sourabh1007** [comment]
It is fixed in latest release.
