### ISSUE TITLE
Refactor RuntimeConfigProvider to be more extensible for Hot Reloading

### ISSUE THREAD

**Issue by aaronburtle** [Azure/data-api-builder#1966]
The current design is to have a single RuntimeConfigProvider class, which stores the RuntimeConfig internally. However, with the addition of hot-reload we need to take into account that a RuntimeConfig is constructed through a different process in Hosted and Local scenarios. To better facilitate hot-reloading, we will move the RuntimeConfig object over to the RuntimeConfigLoader. The RuntimeConfigLoader will therefore be responsible for maintaining the RuntimeConfig object which is consistent with the configuration provided by the user. This means that we need to move the hot-reload functions over to this class, as they are central to initiating the process for deservialization of the new RuntimeConfig object. This will help us to be certain that we do not mix the implementation details of the two scenarios and for example try to monitor a file in the local file system when we are in a hosted scenario.

**Comment by seantleonard** [comment]
Moving this + hot reload related tasks to post GA -> tracking via 1.2rc milestone.

The current PR can be moved to draft or closed for the time being until we revisit this feature post-GA.

**Comment by seantleonard** [comment]
Moving some hot reload tasks to backlog so we can focus on tasks that add hotreload support various services/classes (openapi, authentication config). Once the pre-reqs are done, it will be easier to start updating the runtime config classes directly.
