### ISSUE TITLE
Change default data source name for Hot Reload

### ISSUE THREAD

**Issue by aaronburtle** [Azure/data-api-builder#1967]
We are currently assigning a unique default data source name to each `RuntimeConfig` that we create. However, for a Hot Reload scenario this is problematic because we do not want to be updating this value after the Hot Reload, and so, it can not be uniquely generated each time.

Instead this value should be created in a deterministic way, ie: taking a hash of the connection string.

**Comment by seantleonard** [comment]
> because we do not want to be updating this value after the Hot Reload

need to explain why in the issue so motivation behind this change is clear.

**Comment by seantleonard** [comment]
Not moving this task at the moment, this fix seems necessary even without remaining HR features in this milestone.
