### ISSUE TITLE
[Bug]: Rest endpoints returns 404 on anything but get request when deployed

### ISSUE THREAD

**Issue by baloveless** [Azure/data-api-builder#1974]
### What happened?

I am creating a next.js static web app using a psql database. The problem I am having is when I deploy the SWA on azure the data-api endpoints are not allowing post requests. Here is an example of the behavior captured in postman: 

![image](https://github.com/Azure/data-api-builder/assets/77218586/8f249c1a-f284-43cd-a76a-bef9b98193a0)

Here is what the same calls look like when running the static web app locally: 

![image](https://github.com/Azure/data-api-builder/assets/77218586/27f6ee0c-8dac-4ad9-9dd7-7cb3c6a06fed)

The post requests contain the body 
```
{
    "message":"Tax estimate success",
    "data": "{\"data\":\"none\"}"
}
```

Here are the contents of my staticwebapp.database.config.json file:

```
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/latest/download/dab.draft.schema.json",
  "data-source": {
    "database-type": "postgresql",
    "connection-string": "@env('POSTGRES_URL')",
    "options": {
      "set-session-context": false 
    }
  },
  "runtime": {
    "rest": {
      "enabled": true,
      "path": "/rest"
    },
    "graphql": {
      "enabled": true,
      "path": "/graphql",
      "allow-introspection": true
    },
    "host": {
      "cors": {
        "origins": ["http://localhost:4280", "https://calm-river-08895cf10.3.azurestaticapps.net"],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "development"
    }
  },
  "entities": {
    "Store_Log":{
      "source": {
        "object": "store_log",
        "type": "table"
      },
      "graphql":{
        "type": {
          "singular": "store_log",
          "plural": "store_logs"
        },
        "operation": "query"
      },
      "permissions": [
        {
          "actions": ["*"],
          "role": "anonymous"
        }
      ]
    }
  }
}
```

The static web app is on the free hosting plan. 

For the database I enabled "Allow public access from any Azure service within Azure to this server" 

I've been in contact with support at Compunet but we haven't had any luck determining why this issue is happening. 

Any help would be greatly appreciated. Thank you.

### Version

0.9.7

### What database are you using?

PostgreSQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JaccoK** [comment]
We're experiencing a similar issue, but we're using Next.js with CosmosDB and the /graphql endpoint. Locally everything works fine, but after deployment all post requests to _data-api/graphql_ return 404. Browsing to /data-api returns "Healthy" both locally and in Azure.

An example that works locally but does not work in Azure: https://zealous-island-07e7a8903.4.azurestaticapps.net/api-test/page. In the console you can see it's returning 404 after clicking either list or get.

**Comment by baloveless** [comment]
The issue was solved by some Azure release according to my compunet support contact I'm going to just close thise.
