### ISSUE TITLE
REST endpoint fails to apply filter using a guid value

### ISSUE THREAD

**Issue by davidsk** [Azure/data-api-builder#1999]
### What happened?

An error is returned when attempting to filter using a GUID.  It looks as if it's confusing the value of the filter condition with the column name.  From the log file:
```
[swa] GET http://localhost:5000/rest/Engineer?$filter=UniqueId%20eq%20c033a236268f6d5451fef8b1be5238f8
...
[dataApi] Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: Could not find a property named 'c033a23621fef8b1be5238f8' on type 'default_namespace.Engineer.dbo.Engineers'
```

If I wrap the guid value in quotes, I get a datatype mismatch error.

### Version

Microsoft.DataApiBuilder 0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text
[swa] GET http://localhost:5000/rest/Engineer?$filter=UniqueId%20eq%20c033a236268f6d5451fef8b1be5238f8 (proxy)
[dataApi] info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
[dataApi]       Request starting HTTP/1.1 GET http://localhost:4280/rest/Engineer?$filter=UniqueId%20eq%20c033a236268f6d545e5238f8 application/json -
[swa] GET http://localhost:4280/images/app_logo_384.png - 200
[dataApi] dbug: Azure.DataApiBuilder.Core.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware[0]
[dataApi]       80b40f3b-4924-42f0-a63a-0e4b5ab16393 Request authentication state: Authenticated.
[dataApi] dbug: Azure.DataApiBuilder.Core.AuthenticationHelpers.ClientRoleHeaderAuthenticationMiddleware[0]
[dataApi]       80b40f3b-4924-42f0-a63a-0e4b5ab16393 The request will be executed in the context of the role: authenticated
[dataApi] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
[dataApi]       Executing endpoint 'Azure.DataApiBuilder.Service.Controllers.RestController.Find (Azure.DataApiBuilder.Serv
[dataApi] info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
[dataApi]       Route matched with {action = "Find", controller = "Rest"}. Executing controller action with signature Systeing.Tasks.Task`1[Microsoft.AspNetCore.Mvc.IActionResult] Find(System.String) on controller Azure.DataApiBuilder.Service.Con.RestController (Azure.DataApiBuilder.Service).
[dataApi] fail: Azure.DataApiBuilder.Service.Controllers.RestController[0]
[dataApi]       80b40f3b-4924-42f0-a63a-0e4b5ab16393 Error handling REST request.
[dataApi]       Azure.DataApiBuilder.Service.Exceptions.DataApiBuilderException: Could not find a property named 'c033a23621fef8b1be5238f8' on type 'default_namespace.Engineer.dbo.Engineers'.
[dataApi]        ---> Microsoft.OData.ODataException: Could not find a property named 'c033a236268f6d5451fef8b1be5238f8' onefault_namespace.Engineer.dbo.Engineers'.
[dataApi]          at Microsoft.OData.UriParser.EndPathBinder.GeneratePropertyAccessQueryForOpenType(EndPathToken endPathTogleValueNode parentNode)
[dataApi]          at Microsoft.OData.UriParser.EndPathBinder.BindEndPath(EndPathToken endPathToken)
[dataApi]          at Microsoft.OData.UriParser.MetadataBinder.BindEndPath(EndPathToken endPathToken)
[dataApi]          at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
[dataApi]          at Microsoft.OData.UriParser.BinaryOperatorBinder.GetOperandFromToken(BinaryOperatorKind operatorKind, Qn queryToken)
[dataApi]          at Microsoft.OData.UriParser.BinaryOperatorBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorT
[dataApi]          at Microsoft.OData.UriParser.MetadataBinder.BindBinaryOperator(BinaryOperatorToken binaryOperatorToken)
[dataApi]          at Microsoft.OData.UriParser.MetadataBinder.Bind(QueryToken token)
[dataApi]          at Microsoft.OData.UriParser.FilterBinder.BindFilter(QueryToken filter)
         at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilterImplementation(String filter, ODataUriParserConfiguonfiguration, ODataPathInfo odataPathInfo)
[dataApi]          at Microsoft.OData.UriParser.ODataQueryOptionParser.ParseFilter()
[dataApi]          at Microsoft.OData.UriParser.ODataUriParser.ParseFilter()
[dataApi]          at Azure.DataApiBuilder.Core.Parsers.ODataParser.GetFilterClause(String filterQueryString, String resour
ODataUriResolver customResolver) in /_/src/Core/Parsers/FilterParser.cs:line 57
[dataApi]          --- End of inner exception stack trace ---
[dataApi]          at Azure.DataApiBuilder.Core.Parsers.ODataParser.GetFilterClause(String filterQueryString, String resour
ODataUriResolver customResolver) in /_/src/Core/Parsers/FilterParser.cs:line 61
ctionOperation operationType, String primaryKeyRoute) in /_/src/Core/Services/RestService.cs:line 174
[dataApi]          at Azure.DataApiBuilder.Service.Controllers.RestController.HandleOperation(String route, EntityActionOperation operationType) in /_/src/Service/Controllers/RestController.cs:line 214
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aaronburtle** [comment]
Is it intended that your hexedecimal GUID value not have any hyphens separating the octets?

When I reproduce this locally, I get complaints from SQL if I try to insert into Unique Identifier type columns without having the normal hyphens as separators. So for your example it would be 

`http://localhost:5000/rest/Engineer?$filter=UniqueId eq c033a236-268f-6d54-51fe-f8b1be5238f8`

and then everything works fine. Without those hyphens, the GUID is not being recognized correctly. If you add quotes to the GUID it will instead recognize it as a string of characters and then of course will type mismatch as you pointed out.

This looks correct to me, as the ISO standard for representing GUID as hexidecimal requires that the octets be separated by a hyphen character. Are you intending to store UUIDs in hexadecimal format but without the octets separated by hyphens?

Relevant section below for your convenience.

```
6.4   Hexadecimal representation
For the hexadecimal format, the octets of the binary format shall be represented by a string of hexadecimal digits, using two hexadecimal digits for each octet of the binary format, the first being the value of the four high-order bits of octet 15, the second being the value of the four low-order bits of octet 15, and so on, with the last being the value of the low-order bits of octet 0 (see [6.5](https://www.iso.org/obp/ui/en/#iso:std:iso-iec:9834:-8:ed-3:v1:en:sec:6.5)). A HYPHEN-MINUS (45) character (see ISO/IEC 10646) shall be inserted between the hexadecimal representations of each pair of adjacent fields, except between the "VariantAndClockSeqHigh" field and the "ClockSeqLow" field (see the example in [clause 8](https://www.iso.org/obp/ui/en/#iso:std:iso-iec:9834:-8:ed-3:v1:en:sec:8)).
```

https://www.iso.org/obp/ui/en/#iso:std:iso-iec:9834:-8:ed-3:v1:en:sec:10

**Comment by aaronburtle** [comment]
Just to give some more context for why this particular error message is being returned (ie: why does the parser think that the hexadecimal value you provided should be a property, such as a column or function, but not a literal value). When the query string `$filter=UniqueId%20eq%20c033a236268f6d5451fef8b1be5238f8` is being parsed, Odata is trying to form an Abstract Syntax Tree that would be something like
 
![image](https://github.com/Azure/data-api-builder/assets/93220300/c191e7da-449c-4c7d-aca5-56ab4efd250e)
 
 
And to do so it resolved `eq` to a binary operator, and then it tries to resolve the children nodes in the above image to their correct type and form the AST. When it sees `UniqueId` it resolves this to a kind of EndPath, which represents something like a column or a function in SQL Server. When it sees `c033a236268f6d5451fef8b1be5238f8` because there are no hyphens separating the octets it does not process this as a literal value, but rather it is resolved the same way that `UniqueId` is resolved, as an `EndPath`. Suppose for example that you had a column in your data that was named `c033a236268f6d5451fef8b1be5238f8` and you wanted to return all rows where that column value was equal to `UniqueId` columns value. The only way that the Odata parser can infer that this is **not** the case is if the formatting of the hexadecimal matches a literal type, such as GUID. In this case, it does not, so Odata resolves it as an `EndPath` which leads to it expecting that value to be a property of the model. Which it is not. That leads to the error messaging that we see above.
