### ISSUE TITLE
`dab validate` fetch schema from url error

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#2013]
URL referenced json schemas fail to resolve when using `dab validate`

_Originally posted by @Aniruddh25 in https://github.com/Azure/data-api-builder/pull/2011#discussion_r1478927487_

**Comment by Aniruddh25** [comment]
Faced this issue in 0.11.6-rc too.

**Comment by seantleonard** [comment]
Dependent on #2037
