### ISSUE TITLE
Should mode check be a part of validating relationships?

### ISSUE THREAD

**Issue by ayush3797** [Azure/data-api-builder#2021]
Raising this issue to continue discussion from : https://github.com/Azure/data-api-builder/pull/1929#discussion_r1477179490

**Comment by seantleonard** [comment]
Please add more context here in this issue's description to summarize the problem and what you think we should do. 

With a description about what's in the codebase now and what the proposed change, if any, should be and what the pro's con's are will help us continue discussion.

**Comment by Aniruddh25** [comment]
We should do validations only in `development` mode. Closing since the original validation is also no longer needed.
