### ISSUE TITLE
Nested Create: Finalizing the release plan

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#2025]
Finalize the exact release plan and the details of notifying customers about the feature.

**Comment by seantleonard** [comment]
@severussundar what is the finalized release plan? need to communicate that before closing this issue.

**Comment by severussundar** [comment]
Release plan for Multiple Create: 

For the 0.12 rc1, the following components will be shipped.

1) Schema Generation - https://github.com/Azure/data-api-builder/pull/1902
2) AuthZ validations - https://github.com/Azure/data-api-builder/pull/1943
3) Feature Flag to enable/disable the feature:
        a) CLI changes: https://github.com/Azure/data-api-builder/pull/1983
        b) Re-name the feature to `multiple-create`: https://github.com/Azure/data-api-builder/pull/2103
        c) Engine changes: https://github.com/Azure/data-api-builder/pull/2116 


All these changes are merged to the `main` branch through PR https://github.com/Azure/data-api-builder/pull/2122

Note: With the `0.12.* - rc1` release candidate, users **will not** be able to successfully execute multiple create mutation requests.


For 0.12 rc2, the rest of the changes related to multiple create will be shipped.
1) Removing invalid FK definition from metadata - https://github.com/Azure/data-api-builder/pull/2051
2) Determining the correct order of insertion - https://github.com/Azure/data-api-builder/pull/2056
3) Request validation - https://github.com/Azure/data-api-builder/pull/2057
4) Query Generation, Selection set resolution - https://github.com/Azure/data-api-builder/pull/1994


With the 0.12 rc2, all the changes necessary for the end-to-end working multiple create feature will be shipped. Using the 0.12 rc2 version, users **will be able to successfully execute multiple create mutation requests**.

After releasing 0.12 rc2 candidate, there is scope to receive user reported feedback, bugs, etc., and also bugs identified during bug bash - all of these can be evaluated and incorporated in the 0.12 stable release.
