### ISSUE TITLE
[Bug]: hasNextPage is incorrect at times

### ISSUE THREAD

**Issue by pingu2k4** [Azure/data-api-builder#2029]
### What happened?

When using a SQL database, `hasNextPage` appears to work correctly. When using Cosmos however, when we are on the last page it will sometimes claim there is another page when this isn't the case.

We have a container within Cosmos containing Employees. There are a total of 4 Employees there. When requesting hasNextPage and endCursor, whilst specifying `first: 2` I get the following:
![image](https://github.com/Azure/data-api-builder/assets/11229848/6ee9789e-ab6c-4805-9dc2-02c5f3ca92b8)
Making the same request, but now including the endcursor as the `after`, I get the following:
![image](https://github.com/Azure/data-api-builder/assets/11229848/18e65f72-1945-46d5-ad03-f82e45c6694e)
Note that `hasNextPage` is incorrectly telling us that there is another page, and `endCursor` is not null. Attempting to retrieve the next page returns the following, as expected:
![image](https://github.com/Azure/data-api-builder/assets/11229848/73f642d2-866e-4e01-91bb-63cf4a27253a)

If I instead request 3 items at once, it all works fine. This is the response asking for 3 per page, and the second page:
![image](https://github.com/Azure/data-api-builder/assets/11229848/5dbb5a76-3384-4be9-ae00-87a777f76cb3)
It knows that it is the last page as the items returned are < what were requested.

### Version

0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
@pingu2k4 Thank you for reporting. We'll take a look.

**Comment by sourabh1007** [comment]
In Cosmos DB, `pagesize` is upper bound value, which is different than, how it works for a relational database like SQL, which says, number of results cannot exceed the size but there can be less number of documents in each page (includes empty results).

Conceptually, how pagination works in cosmos DB, you can ref. https://learn.microsoft.com/en-us/azure/cosmos-db/nosql/query/pagination#query-executions
Query results depends on many other factors which are defined here, ref. https://learn.microsoft.com/en-us/azure/cosmos-db/concepts-limits#sql-query-limits

DAB create Cosmos DB SQL queries, behind the scene, to fetch this data, so it is recommended to design your data model considering this restriction in mind.
