### ISSUE TITLE
[Bug]: Inconsistency with endCursor

### ISSUE THREAD

**Issue by pingu2k4** [Azure/data-api-builder#2030]
### What happened?

With SQL as the backing DB, `endCursor` will not be null and will provide a value when `hasNextPage` is false. I would expect `endCursor` to be null here.

When using Cosmos as the DB, and when not encountering the bug in #2029, when `hasNextPage` is false, `endCursor` will also be null, as expected.

### Version

0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
hi @pingu2k4 thanks for reporting, just to clarify, in this issue `hasNextPage` works but the `endCursor` is improperly populated for MSSQL?

**Comment by pingu2k4** [comment]
Yes, thats correct, and thanks. :)
