### ISSUE TITLE
Improve documentation for deploying DAB using Azure Container Apps via portal

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#2053]
The sample script provided in the repo here: https://github.com/Azure/data-api-builder/blob/main/samples/azure/azure-container-apps-deploy.sh doesn't map 1:1 to a Portal Experience of creating a Container App using DAB. 

The doc section here: https://learn.microsoft.com/en-us/azure/data-api-builder/running-in-azure#use-azure-container-apps is not sufficient to resolve issues like config file is not found due to incorrect mapping of the storage account.

This issue is to improve our documentation to improve documentation for deploying DAB using ACA via the Azure portal.

**Comment by seesharprun** [comment]
Pre-requisites for #2054

**Comment by seantleonard** [comment]
This is the most critical tutorial to complete. We've had many customers ask about Container Apps and I know there are also many who currently use container apps. Regardless of Azure Portal frequently updating UI, a point in time reference that shows step by step instructions is still important. If the UI changes, we can always update, but at least with a baseline, readers can infer what needs to be done given new UI elements.

**Comment by seesharprun** [comment]
The ACA deployment guide will be published later today.

**Comment by seesharprun** [comment]
<https://learn.microsoft.com/azure/data-api-builder/how-to-deploy-container-app>
