### ISSUE TITLE
[Bug]: Custom roles don't work with SWA provider

### ISSUE THREAD

**Issue by itpropro** [Azure/data-api-builder#2074]
### What happened?

Custom roles in permissions don't work with Static Web Apps. 
I have a Static Web App with the auth being configured like this (staticwebapp.config.json):

```
  "auth": {
    "rolesSource": "/api/getRoles",
    "identityProviders": {
      "azureActiveDirectory": {
        "userDetailsClaim": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name",
        "registration": {
          "openIdIssuer": "https://login.microsoftonline.com/{REPLACED_IN_REAL_CONFIG}",
          "clientIdSettingName": "AAD_CLIENT_ID",
          "clientSecretSettingName": "AAD_CLIENT_SECRET"
        },
        "login": {
          "loginParameters": [
            "resource=https://graph.microsoft.com"
          ]
        }
      }
    }
  }
```

My host config is like this (staticwebapp.database.config.json):

```
    "host": {
      "cors": {
        "origins": [
          "http://localhost:4280"
        ],
        "allow-credentials": true
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "production"
    }
```

Now when on any entity another role than `authenticated` or `anonymous` is used, the request always fails with a GQL error that the current user is not authenticated for that specific path. This is a entity example:

```
  "entities": {
    "ExampleEntity": {
      "source": "exampleEntities",
      "permissions": [
        {
          "role": "custom-reader",
          "actions": [
            {
              "action": "create"
            },
            {
              "action": "read"
            },
            {
              "action": "update"
            },
            {
              "action": "delete"
            }
          ]
        }
      ]
    }
  }
```

This error occurs in the local SWA CLI emulator as well as on the live environment. The custom role (in the above example `custom-reader`) is existent on the token and in the cookie.
I also realized that even when removing the `authenticated` role from the userRoles array, craft that into a cookie and inject that into the request (which changes what is redirected in the auth header by the swa cli proxy) it still works, so it seems like for some reason the complete userRoles array is not parsed or used in any way.

### Version

The one integrated with the current SWA CLI 0.9.7 also tested with 0.10.23

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

GraphQL
```
{
    "errors": [
        {
            "message": "The current user is not authorized to access this resource.",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "exampleEntities"
            ],
            "extensions": {
                "code": "AUTH_NOT_AUTHORIZED"
            }
        }
    ]
}
```

SWA CLI
```
[dataApi] fail: Azure.DataApiBuilder.Service.Startup[0]
[dataApi]       Error code: AUTH_NOT_AUTHORIZED
[dataApi] Error message: The current user is not authorized to access this resource.
[dataApi] info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
[dataApi]       Executed endpoint 'Hot Chocolate GraphQL Pipeline'
[dataApi] info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
[dataApi]       Request finished HTTP/1.1 POST http://localhost:4280/graphql application/json 440 - 500 - application/json;+charset=utf-8 476.4775ms
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Hi @itpropro,

In your GraphQL request, make sure to include the HTTP header:
`X-MS-API-ROLE` with value `custom-reader`

For more details with examples, see https://learn.microsoft.com/azure/data-api-builder/authorization#user-roles

**Comment by itpropro** [comment]
> Hi @itpropro,
> 
> In your GraphQL request, make sure to include the HTTP header: `X-MS-API-ROLE` with value `custom-reader`
> 
> For more details with examples, see https://learn.microsoft.com/azure/data-api-builder/authorization#user-roles

This is not feasable when the data-builder is used with the SWA. There is a clear separation of concern between auth and application logic, especially with SPAs.
There is no secure way to delegate the inclusion of the X-MS-API-ROLE header to the application, this has to be done by the SWA proxy or the data-builder has to parse the provided headers injected by the SWA proxy, otherwise it would be a huge security issue.

**Comment by seantleonard** [comment]
The `X-MS-API-ROLE` header is a hint to DAB as to which role DAB should execute the request. DAB doesn't just honor that value and instead validates the value against authenticated user's role memberships specified in the SWA injected `x-ms-client-principal` header.

DAB doesn't perform additive permissions resolution. e.g. if a user is a member of { role1, role2, role3 }, DAB doesn't know which role permissions to evaluate unless you provide the `X-MS-API-ROLE` hint. If that header isn't provided, an authenticated user is implicitly a member of the SWA injected `authenticated` role. Unauthenticated users are implicitly in the SWA injected role `anonymous`.

SWA docs describes the usage of the `X-MS-API-ROLE` header here: [https://learn.microsoft.com/en-us/azure/static-web-apps/database-overview](https://learn.microsoft.com/en-us/azure/static-web-apps/database-overview#:~:text=The%20REST%20or%20GraphQL%20request%20must%20include%20a%20header%20with%20the%20key%20of%20X%2DMS%2DAPI%2DROLE%20and%20a%20value%20of%20the%20role%20name%20matching%20what%27s%20listed%20in%20the%20entity%20configuration%20rules.)

**Comment by itpropro** [comment]
Thanks for the fast reply @seantleonard!
I didn’t find that docs page and I think I haven’t understood the process completely, yet.
So assuming I have the custom-reader role, that one needs to be present on the header as well as in the SWA context. If I provide the `x-ms-api-role` header and hint to a role that is not present in the swa headers userRole list, it will still deny the request, correct?

I am just not understanding why the header is needed, as it adds additional friction to the usage of an SWA, as the whole concept is that the auth is completely transparent to the application and can be completely configured by config files.
Is there any reason, why the current implementation not just uses the already parsed userRoles array from the SWA header and uses the first role that matches the required permission for that route?

**Comment by seantleonard** [comment]
Hi @itpropro, happy to answer and discuss this.

> If I provide the x-ms-api-role header and hint to a role that is not present in the swa headers userRole list, dab will still deny the request, correct?

You are correct. DAB will deny the request in that scenario. If the user attempts to spoof/bypass this by providing their own SWA header (`x-ms-client-principal`), the user's header will be ignored since SWA drops any user provided instances of that header and injects its own.

>  Is there any reason, why the current implementation not just uses the already parsed userRoles array from the SWA header and uses the first role that matches the required permission for that route?

Yes, there are two reasons:
1. We aren't guaranteed a specific ordering of roles in the `userRoles` array. The `userRoles` array is populated by an identity provider (AzureAD/EntraID, Okta, Auth0, Facebook, X/Twitter), or SWA attached Azure Function where we aren't universally guaranteed a specific ordering of roles. 
   - (Yes, I suppose you could enforce that in your own Azure Function, that would be the only case to enforce ordering but still isn't universal across the mechanisms that can source the userRoles array). 
2. By requiring the x-ms-api-role header hint, DAB doesn't have to guess which role context the app intends to execute a request. DAB enables the Static Web App to explicitly define which role context a request should execute as.

**Comment by itpropro** [comment]
Thanks for the explanation! I was aware of the stripping of the `x-ms-client-principal`, I just wasn't sure how exactly dab handles the two headers in combination. 

For the actual implementation what I meant was that dab collects the roles that could do the request (for example all roles that have the read permission assigned on a specific entity) and then checking if any one of them is included in the array.
But I understand that this could have performance impacts, if you have a complex permission concept on a sub-query basis, where you would have to travers upwards in the permission graph to collect all roles that cover the specific entity/field.

For the SWA documentation I just skipped over the "Overview" page and went straight to the "Configuration" page and was initially confused by the sentence "The same role-based authentication rules used to secure paths also secure database entities, and can be used to define permissions for each entity. The entities object also specifies the relationships between entities.".
Maybe this information can be included in some other pages, as the link you sent me is literally the only point in the whole azure-docs repo where that header is mentioned (and I of course missed that part 😅 )

PS: Are you for any chance available next week during the MVP summit?

**Comment by seantleonard** [comment]
> For the actual implementation what I meant was that dab collects the roles that could do the request (for example all roles that have the read permission assigned on a specific entity) and then checking if any one of them is included in the array.
But I understand that this could have performance impacts, if you have a complex permission concept on a sub-query basis, where you would have to travers upwards in the permission graph to collect all roles that cover the specific entity/field.

While this may be simpler to apply to permissions set only at the entity level, this would get more complicated when applying field level authorization and, lastly, row level authorization (for Azure SQL/ SQL Server cases, if configured).

> I see multiple issues with the current implementation and using it in web applications. It requires the application to implement code for every component that makes a GQL request. Normally a gql client is injected at a higher level in Vue or React and is then used transparently.
Requiring a specific header makes things very complex. Especially as you cannot just hand over all user roles, but have to implement selection logic in the frontend, meaning you have to replicate the whole permission concept there.

Can you provide an example of this? or rather what the expectation and what happens for your app's front end when a request is forbidden (Authz failure)? 

> EDIT: Another thing that just came to my mind is the combination of multiple roles. Some applications may have a "reader" role and some additional specific ones for parts of the application. You could model that in SWA as well as in the DAB config, but in the frontend you would have to implement a check on a per field level (worst case) for each request, which would be an anti-pattern, as you normally just react to feedback from the backend and want to keep the auth layer and it's config at one place.
This would also generate a lot of problems for teams, as you would not be able to work on front- and backend independently.

>
> I also found another issue that mentions a solution for this, do you know if there was any progress on https://github.com/Azure/data-api-builder/issues/1240 ?

Can you provide an example for this: _"but in the frontend you would have to implement a check on a per field level (worst case) for each request"_ That would help me understand more why you'd require performing/duplicating authorization model on the front end. There are no further updates for #1240, it's still in discussion and we welcome any ideas to get around the issue of indeterminate behavior suggested thus far.

I'm not sure about my availability at MVP summit but @yorek will be there! I'm still happy to connect though.

**Comment by yorek** [comment]
Absolutely, @itpropro let's meet at MVP Summit. I'll follow up via email :)

**Comment by yorek** [comment]
Btw, I was able to use roles when using SWA custom authentication, see:

- https://github.com/Azure-Samples/azure-sql-db-session-recommender?tab=readme-ov-file#optional-use-a-custom-authentication-provider-with-static-web-apps
- https://github.com/Azure-Samples/azure-sql-db-session-recommender/blob/main/api/AuthenticationProcessor.cs

Have you tried that road already?

**Comment by itpropro** [comment]
> Btw, I was able to use roles when using SWA custom authentication, see:
> 
> * https://github.com/Azure-Samples/azure-sql-db-session-recommender?tab=readme-ov-file#optional-use-a-custom-authentication-provider-with-static-web-apps
> * https://github.com/Azure-Samples/azure-sql-db-session-recommender/blob/main/api/AuthenticationProcessor.cs
> 
> Have you tried that road already?

Sorry if I was not clear, the usage of `X-MS-API-ROLE` as explained by @seantleonard fixed the original problem (thanks again for the explanation), it's just not suitable in a real world scenario.
I will close this issue for now and will prepare some scenarios we can discuss next week :)
