### ISSUE TITLE
Protect DAB endpoints against DDOS attacks

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#2098]
Original ask from user: [Discussions link](https://github.com/Azure/data-api-builder/discussions/2093)

To protect DAB GraphQL endpoint against DDOS attack,

1) Limit the size of GraphQL query response. Related issue: [#1577](https://github.com/Azure/data-api-builder/issues/1577)
2) Introduce a property in the config file to make timeout (for the GraphQL API response) configurable.

**Comment by seantleonard** [comment]
Let's use the original item instead of creating a duplicate. The original is more targeted at what capability we are trying to add. This issue is a positive side effect.
