### ISSUE TITLE
[Bug]: CLI returns code 0 when in fact there was an error

### ISSUE THREAD

**Issue by pingu2k4** [Azure/data-api-builder#2110]
### What happened?

When any command given to the DAB CLI results in an error, the error is output however the returned code is a code 0, indicating success. It would be more helpful if this was more indicative of an issue in the command, as it makes it far more difficult to automate anything if we can't easily tell the success or failure of a command.

For an example, try running a `dab add` command, whilst specifying `--config` and pointing it to a non existent file.

### Version

0.9.7+e560142426d1c080b9fd7b7fabff51a276f6bf61

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Thanks for reporting. Tracked via #1777 and fix is being reviewed in PR #2084

**Comment by Aniruddh25** [comment]
Closing as fixed.
