### ISSUE TITLE
Enhance logic for determining the referencing entity when fields backed by a column with default value is present. 

### ISSUE THREAD

**Issue by severussundar** [Azure/data-api-builder#2148]
Original comment: https://github.com/Azure/data-api-builder/pull/2056#discussion_r1547552288

When determining the referencing entity by considering the input request body, evaluate whether it is possible to determine the referencing entity when the data for relationship fields backed by a column with default value is absent in the input mutation request.

**This discussion is inapplicable when there exist foreign key constraints defined at the database layer. Only applicable when relationship is defined only in the config file**

**Some scenarios to evaluate:**

*Scenario where it should be possible to determine the referenced/referencing entity:*

Consider two entities: 
Entity A ---> Relationship fields: [A1, A2]. Field A2 is backed by a column with a default value.  
Entity B ---> Relationship fields: [B1, B2]. 

In the mutation request, if there is data for A1 and no data for A2, B1, B2; it should be possible for us to say Entity B is the referencing entity since, insertion in Entity A will succeed because we have values for A1, A2 (and rest of the columns).  As long as the combination of <A1, A2> is unique, it should be possible to use this to link it with a row in <B1,B2>

*Scenarios where it is not possible to determine the referencing/referenced entity:*

Consider two entities: 
Entity A ---> Relationship fields: [A1, A2]. Field A2 is backed by a column with a default value.  
Entity B ---> Relationship fields: [B1, B2].  Field B2 is backed by a column with a default value.

In the mutation request, if there is data for A1, B1 and no data for A2 and B2; Since, both A2 and B2 are backed by columns with default values, insertion in either one can succeed. It is not possible to determine which is the referencing entity here. 

Evaluate if the logic for order determination should interpret relationship fields with the default values when not provided in the input request by the user.

**Comment by seantleonard** [comment]
@severussundar please update expectations and description for this feature.

**Comment by severussundar** [comment]
**Relationship fields when backed by default values will be required to be provided by the user**.

Consider two entities: `User_AutogenToNonAutogenRelationshipColumn` and `UserProfile` 

Entity `User_AutogenToNonAutogenRelationshipColumn` has the following relationship defined with entity `UserProfile`.

```json
"UserProfile_AutogenToNonAutogenRelationshipColumn": {
          "cardinality": "one",
          "target.entity": "UserProfile",
          "source.fields": [
            "userid",
            "username"
          ],
          "target.fields": [
            "userid",
            "username"
          ],
          "linking.source.fields": [],
          "linking.target.fields": []
        }

```
**Relationship Fields**

**User_AutogenToNonAutogenRelationshipColumn:** `userid`, `username`
**UserProfile:** `userid`, `username`. `userid` column has a **default value of 1**.

**Multiple Create request:**
![Mutation Request](https://github.com/Azure/data-api-builder/assets/11196553/c0b85541-a58f-465c-8612-46439e38d888)

```graphql
mutation {
  createUser_AutogenToNonAutogenRelationshipColumn(
    item: {
      email: "alice@example.com"
      UserProfile_AutogenToNonAutogenRelationshipColumn: {
        profilepictureurl: "https://example.com/profiles/alice"
        username: "Alice"
      }
    }
  ) {
    userid
    username
    email
    UserProfile_AutogenToNonAutogenRelationshipColumn {
      profileid
      username
      userid
      profilepictureurl
    }
  }
}
```

The above mutation request does not provide an input for `userid` field for the relationship field `UserProfile_AutogenToNonAutogenRelationshipColumn`. It only provides input for `username`.  When executed this request, it will error out with the following error message.

**Error Message:**
![Error Message](https://github.com/Azure/data-api-builder/assets/11196553/5b8aca42-86ba-4f20-b145-3ed48c36c173)


```json
{
  "errors": [
    {
      "message": "Neither source entity: User_AutogenToNonAutogenRelationshipColumn nor the target entity: UserProfile for the relationship: UserProfile_AutogenToNonAutogenRelationshipColumn at level: 1 provide sufficient data to perform a multiple-create (related insertion) on the entities.",
      "extensions": {
        "code": "BadRequest"
      }
    }
  ],
  "data": {
    "createUser_AutogenToNonAutogenRelationshipColumn": null
  }
}
```

**Comment by Aniruddh25** [comment]
Require values to be provided even for columns which have defaults to determine referencing and referenced entities.
