### ISSUE TITLE
Cosmos: Map multiple types to the same container with same logical PK

### ISSUE THREAD

**Issue by kirankumarkolli** [Azure/data-api-builder#216]
Optimized state for Cosoms is to co-locate all the entities/types in the same container with the same logical PK.
=> this model needs to cover below two parts in the model
- Container PK mapping to the type (ref: #215 )
- Type to Item/Document mapping OR de-normalize the payload fully? 

Let's discuss it and explore the possibilities.

**Comment by seantleonard** [comment]
Adding @sajeetharan and @sourabh1007 to re-evaluate this ask.
