### ISSUE TITLE
[Known Issue]: https://localhost:5001 not in Console Logs after `dab start`

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#2237]
### What happened?

When using .NET 8 and Data API builder v1.1+ CLI, the Console Logs do not present the HTTPS URL.

## Workaround

In your `.env` file, add the following line: 

```bash
ASPNETCORE_URLS="http://localhost:5000;https://localhost:5001"
```
### References

1. https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
2. https://learn.microsoft.com/en-us/azure/data-api-builder/how-to-use-environments#create-environment-variables-file

### Version

1.1+

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST, GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by glick1** [comment]
Anyone able to get this running with SSL and self gen certificate pfx file? https://learn.microsoft.com/en-us/azure/data-api-builder/how-to-run-container#pull-and-run-the-docker-container-image

docker run \
    --name dab \
    --publish 5000:5000 \
    --detach \
    --mount type=bind,source=$(pwd)/dab-config.json,target=/App/dab-config.json,readonly \
    mcr.microsoft.com/azure-databases/data-api-builder


"_This guide uses a HTTP connection. When running a Data API builder container in Docker, you'll see that only the HTTP endpoint is mapped. **If you want your Docker container to support HTTPS for local development, you need to provide your own SSL/TLS certificate and private key files required for SSL/TLS encryption and expose the HTTPS port.** A reverse proxy can also be used to enforce that clients connect to your server over HTTPS to ensure that the communication channel is encrypted before forwarding the request to your container_."

**Comment by seantleonard** [comment]
The corrected breaking change article is for .net7: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/https-binding-kestrel
