### ISSUE TITLE
[Enhancement]: Introduce `dab configure`

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#2251]
Today, it's a bit of a trick to know which verb to use in order to add, update, or modify non-entity information in the configuration file. This new verb `configure` is intended to set all data outside of entity information - entity information is handled by the `add / update / delete` verbs and is already (mostly) comprehensive.

| Configuration File Property Path                                        | CLI Flag                                                           | Data Type | Nullable |
|-------------------------------------------------------------------------|--------------------------------------------------------------------|-----------|----------|
| data-source.<br/>database-type                                          | <nobr>--data-source.database-type</nobr>                           | String: `MSSQL`, `PostgreSQL`, `CosmosDB`, `MySQL` | ❌ |
| data-source.<br/>connection-string                                      | <nobr>--data-source.connection-string</nobr>                       | String    | ❌       |
| data-source.<br/>options.database                                       | <nobr>--data-source.options.database</nobr>                        | String    | ✅       |
| data-source.<br/>options.container                                      | <nobr>--data-source.options.container</nobr>                       | String    | ✅       |
| data-source.<br/>options.schema                                         | <nobr>--data-source.options.schema</nobr>                          | String    | ✅       |
| data-source.<br/>options.set-session-context                            | <nobr>--data-source.options.set-session-context</nobr>             | Boolean: `true`, `false` (default: `false`) | ✅ |
| data-source-files                                                       | <nobr>--data-source-files</nobr>                                   | Array of strings | ✅ |
| runtime.<br/>rest.path                                                  | <nobr>--runtime.rest.path</nobr>                                   | String (default: `/api`) | ❌       |
| runtime.<br/>rest.enabled                                               | <nobr>--runtime.rest.enabled</nobr>                                | Boolean: `true`, `false` (default: `true`) | ❌ |
| runtime.<br/>rest.request-body-strict                                   | <nobr>--runtime.rest.request-body-strict</nobr>                    | Boolean: `true`, `false` (default: `true`) | ✅ |
| runtime.<br/>graphql.allow-introspection                                | <nobr>--runtime.graphql.allow-introspection</nobr>                 | Boolean: `true`, `false` (default: `true`) | ✅ |
| runtime.<br/>graphql.path                                               | <nobr>--runtime.graphql.path</nobr>                                | String (default: `/graphql`) | ❌       |
| runtime.<br/>graphql.enabled                                            | <nobr>--runtime.graphql.enabled</nobr>                             | Boolean: `true`, `false` (default: `true`) | ❌ |
| runtime.<br/>graphql.multiple-mutations.create.enabled                  | <nobr>--runtime.graphql.multiple-mutations.create.enabled</nobr>   | Boolean: `true`, `false` (default: `true`) | ✅ |
| runtime.<br/>host.mode                                                  | <nobr>--runtime.host.mode</nobr>                                   | String: `Development`, `Production` | ❌ |
| runtime.<br/>host.cors.origins                                          | <nobr>--runtime.host.cors.origins</nobr>                           | Array of strings | ✅ |
| runtime.<br/>host.cors.allow-credentials                                | <nobr>--runtime.host.cors.allow-credentials</nobr>                 | Boolean: `true`, `false` (default: `false`) | ✅ |
| runtime.<br/>host.authentication.provider                               | <nobr>--runtime.host.authentication.provider</nobr>                | String: `StaticWebApps`, `AppService`, `AzureAD`, `Jwt` | ✅ |
| runtime.<br/>host.authentication.jwt.audience                           | <nobr>--runtime.host.authentication.jwt.audience</nobr>            | Array of strings | ✅ |
| runtime.<br/>host.authentication.jwt.issuer                             | <nobr>--runtime.host.authentication.jwt.issuer</nobr>              | String    | ✅       |
| runtime.<br/>cache.enabled                                              | <nobr>--runtime.cache.enabled</nobr>                               | Boolean: `true`, `false` (default: `false`) | ✅ |
| runtime.<br/>cache.ttl-seconds                                          | <nobr>--runtime.cache.ttl-seconds</nobr>                           | Integer (default: `3600`) | ✅       |
| runtime.<br/>telemetry.application-insights.connection-string           | <nobr>--runtime.telemetry.application-insights.connection-string</nobr> | String  | ✅       |
| runtime.<br/>telemetry.application-insights.enabled                     | <nobr>--runtime.telemetry.application-insights.enabled</nobr>      | Boolean: `true`, `false` (default: `false`) | ✅ |
| runtime.<br/>host.log-level                                             | <nobr>--runtime.host.log-level</nobr>                              | String: `Debug`, `Information`, `Warning`, `Error`, `Fatal` (default: `Information`) | ✅ |

Some of these values will be set in `dab init` and there is no plan to change this. The purpose of `dab configure` is to ensure the CLI is comprehensive and to allow individual modifications through the CLI.

**Comment by abhishekkumams** [comment]
completed in mentioned PRs
