### ISSUE TITLE
[Test Bug] Fix GraphQLSupportTypesTestsBase.cs datarows for QueryTypeColumn test. 

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#2255]
The following datarows are duplicates and just need to specify id values 1,2,3,4, respectively.
![image](https://github.com/Azure/data-api-builder/assets/6414189/06c94e31-c8ba-4bbd-a061-ed67b1d197de)

https://github.com/Azure/data-api-builder/blob/7215f1a499b6f61dce200ffe92f6f0cbdb44e49e/src/Service.Tests/SqlTests/GraphQLSupportedTypesTests/GraphQLSupportedTypesTestsBase.cs#L72-L74

**Comment by Surya056** [comment]
I'm happy to fix this issue
