### ISSUE TITLE
[Bug]: Float fields get saved based on local Windows Regional format setting

### ISSUE THREAD

**Issue by evacotelin** [Azure/data-api-builder#2284]
### What happened?

I have the following GraphQL schema definition:

```
type AppReport @model {
  id: ID
  description: String
  latitude: Float
  longitude: Float
  created: DateTime
}
```

When executing the following mutation, the Float fields (i.e. latitude & longitude) get saved as integers (the decimal separator is removed, not really converted to integer). 
![image](https://github.com/Azure/data-api-builder/assets/145988561/2418c210-ef79-4327-ad35-02afc684eba3)

This is due to my Windows _Regional format_ setting, because the comma (,) is used as the default decimal separator: 
![image](https://github.com/Azure/data-api-builder/assets/145988561/09e840e8-781b-4e1c-88ef-db944a4319d1)

When changing my Windows Regional format setting to _English (United States)_ the GraphQL mutation works as expected: saves latitude & longitude fields as Floats (because the point (.) is used as the default decimal separator).

### Version

1.1.7+74ea6c5f37f8629fd7f8b13fc56027bf0bf0a93a

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sourabh1007** [comment]
Fixed.
