### ISSUE TITLE
Replace copies of RuntimeConfig with RuntimeConfigProvider

### ISSUE THREAD

**Issue by aaronburtle** [Azure/data-api-builder#2321]
There are classes we currently use, such as the SqlMetaDataProvider, OpenApiDocumentor, and CostmosSqlMetaDataProvider, that save internal copies of the RuntimeConfig. These classes instead should have a copy of the RuntimeConfigProvider, and when a runtimeconfig is needed they should instead get that runtimeconfig from the provider as needed. This will cause the runtimeconfig to always be the most up to date copy.

**Comment by seantleonard** [comment]
@aaronburtle the design doc is not publicly accessible. Doesn't need to be referenced here unless you end up created a markdown file to include in this repo

**Comment by aaronburtle** [comment]
> @aaronburtle the design doc is not publicly accessible. Doesn't need to be referenced here unless you end up created a markdown file to include in this repo

thanks for pointing that out Sean, ill remove from these issues.
