### ISSUE TITLE
Hot-Reload Authorization rules

### ISSUE THREAD

**Issue by aaronburtle** [Azure/data-api-builder#2324]
While we currently deserialize the new entities into our object mapping that makes up the runtimeconfig, we do not update the GraphQL Schema. For entities to properly hot-reload, we need the GraphQL Schema to update as new entities are added or old entities are removed.

We also do not currently refresh the AuthorizationResolver. This too needs to be refreshed to reflect the new authorization configuration as it is in the newly hot-reloaded entity section.

**Comment by seantleonard** [comment]
GraphQL:
- https://github.com/ChilliCream/hotchocolate-examples/tree/master/misc/TypeModules
- https://chillicream.com/blog/2021/09/27/hot-chocolate-12#dynamic-schemas
