### ISSUE TITLE
Refresh Authentication as part of a Hot-Reload scenario.

### ISSUE THREAD

**Issue by aaronburtle** [Azure/data-api-builder#2325]
In the case that during a hot-reload we are changing the authentication being used, we need to refresh the authentication metadata.

**Comment by seantleonard** [comment]
isn't this a dupe of #1969 ?

**Comment by aaronburtle** [comment]
> isn't this a dupe of #1969 ?

yes, will close as dupe

**Comment by Aniruddh25** [comment]
Dupe
