### ISSUE TITLE
[Bug]: Exporting GraphQL schema does not work with cosmosdb emulator

### ISSUE THREAD

**Issue by sander1095** [Azure/data-api-builder#2332]
### What happened?

After following [this quickstart](https://learn.microsoft.com/en-us/azure/data-api-builder/quickstart-nosql) I would like to export the graphql schema using `dab export` like so (using Windows 11)

```
dab export --graphql -o test.graphql -c .\dab-config.json
```

However, this fails with the logs mentioned below.

I find this to be odd. Perhaps I misunderstand the `export` feature, but based on this input I would expect it to work:

<details>
  <summary><code>dab-config.json</code></summary>

```json
{
  "$schema": "https://github.com/Azure/data-api-builder/releases/download/v1.1.7/dab.draft.schema.json",
  "data-source": {
    "database-type": "cosmosdb_nosql",
    "connection-string": "AccountEndpoint=https://localhost:8081;AccountKey=C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==;",
    "options": {
      "database": "bookshelf",
      "container": null,
      "schema": "schema.graphql"
    }
  },
  "runtime": {
    "rest": {
      "enabled": false,
      "path": "/api",
      "request-body-strict": true
    },
    "graphql": {
      "enabled": true,
      "path": "/graphql",
      "allow-introspection": true
    },
    "host": {
      "cors": {
        "origins": [],
        "allow-credentials": false
      },
      "authentication": {
        "provider": "StaticWebApps"
      },
      "mode": "development"
    }
  },
  "entities": {
    "Author": {
      "source": {
        "object": "authors"
      },
      "graphql": {
        "enabled": true,
        "type": {
          "singular": "Author",
          "plural": "Authors"
        }
      },
      "rest": {
        "enabled": false
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            {
              "action": "*"
            }
          ]
        }
      ]
    }
  }
}
```
</details>

<details>
<summary><code>schema.graphql</code></summary>

```graphql
type Author @model {
  id: ID!
  firstName: String!
  middleName: String
  lastName: String!
}
```
</details>

When using the `/graphql` endpoint and executing the following query, I do get data back, so it seems like everything else is working just fine.

```graphql
query {
  authors {
    items {
      id
      firstName
      lastName
    }
  }
}
```

### Version

Microsoft.DataApiBuilder 1.1.7+74ea6c5f37f8629fd7f8b13fc56027bf0bf0a93a

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
Information: User provided config file: .\dab-config.json
Loading config file from .\dab-config.json.
Information: User provided config file: .\dab-config.json
Loading config file from .\dab-config.json.
Information: Loaded config file: .\dab-config.json
Information: Setting minimum LogLevel: None.
Starting the runtime engine...
Loading config file from .\dab-config.json.
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[63]
      User profile is available. Using 'C:\Users\stenb\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\projects\Personal\cosmosdb-emulator
Error: Failed to export GraphQL schema.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sourabh1007** [comment]
1. `export` has nothing to do with Cosmos DB Emulator (or Account) as of now, it actually uses DAB service to fetch the schema  information ref. https://github.com/Azure/data-api-builder/blob/e8d9fcb9ac1c2aa8b47808b0a658a09e092545e0/src/Cli/Exporter.cs#L75
2. Did you make sure, you have your DAB Service started before running `export` command?

**Comment by sander1095** [comment]
Gotcha! Perhaps some docs about this, or actually implementing this feature to export the schema from cosmosdb would be great! ❤️

**Comment by abhishekkumams** [comment]
@sander1095, This is happening because export method uses `https` to generate and export the schema file. The default HTTPS address and port have been removed from Kestrel in .NET 7. here's a link for ref: https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/https-binding-kestrel

Use this as a workaround:
![image](https://github.com/user-attachments/assets/5aaafdc3-759c-4749-9f49-caf736a97830)

**Comment by abhishekkumams** [comment]
I also created a work item to address this fix: #2352

**Comment by sander1095** [comment]
@abhishekkumams And how about extending the export command to export a graphql schema from cosmosdb to use with DAB? Having to do it by hand is a bit painful, and I believe `dab export` or `dab export cosmosdb` or something could be really useful!

**Comment by abhishekkumams** [comment]
> @abhishekkumams And how about extending the export command to export a graphql schema from cosmosdb to use with DAB? Having to do it by hand is a bit painful, and I believe `dab export` or `dab export cosmosdb` or something could be really useful!

We already have an open PR for this: https://github.com/Azure/data-api-builder/pull/2288

**Comment by abhishekkumams** [comment]
This issue is addressed in the PR: https://github.com/Azure/data-api-builder/pull/2375
