### ISSUE TITLE
[Bug]: Missing pagination property in dab.draft.schema.json

### ISSUE THREAD

**Issue by mart2n** [Azure/data-api-builder#2333]
### What happened?

I added the pagination section in the runtime section of the config file as following:

`"pagination": {
            "max-page-size": -1, 
            "default-page-size": 100 
          }`

`dab start` works fine, but to generate the merged config file I use `dab validate` and this fails, because the "pagination" section is missing in the dab.draft.schema.json file

### Version

1.1.7

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI), Container Apps

### Which API approach are you accessing DAB through?

GraphQL

### Relevant log output

```Text
...
Error: > Total schema validation errors: 1
> NoAdditionalPropertiesAllowed: #/runtime.pagination at 41:17


Error: Config is invalid. Check above logs for details.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Thank you for reporting! We'll work on a fix for this.
