### ISSUE TITLE
Add test for capitalization collations

### ISSUE THREAD

**Issue by RubenCerna2079** [Azure/data-api-builder#2350]
Need to add new tests related to collations based on capitalization. Related to main issue #1535.
 
Some examples of this would be to ensure it works with both cases `SELECT json_agg(to_jsonb(table0)) FROM (SELECT title FROM books ORDER BY title asc) as table0` and `SELECT json_agg(to_jsonb(table0)) FROM (SELECT TITLE FROM BOOKS ORDER BY TITLE asc) as table0`.

**Comment by seantleonard** [comment]
might be helpful have an example of what you want to test
