### ISSUE TITLE
[Bug]: `DAB_ENVIRONMENT` env var set with `folder/dab-config.json` is processed incorrectly

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#2376]
### What happened?

A bug happened!

`FileSystemRuntimeConfigLoader::GetFileName(string? environmentValue, bool considerOverrides)`
does not generate a correct file name/path when the input arg `environmentValue` is something like `folder/dab-config.json`

Here are the var values as shown in the debugger:
![image](https://github.com/user-attachments/assets/5fcb9562-bf4d-4cbc-af6a-67d9f4895a11)

### Version

1.2

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhishekkumams** [comment]
I don't see this as a bug. The ENV variable is supposed to contain the Environment name such as Development, Prod, etc. Providing a file path is incorrect and should be treated as a user error.

We can improve our doc to be more specific like:
```
### ENV Variable

The `ENV` variable is used to determine the environment-specific configuration file. The file name is constructed as `abc.{ENV}.json`.

### Expected Values

The `ENV` variable should contain only valid environment names. Examples of valid environment names include:

- `prod`
- `dev`
- `staging`
- `prod1`

### Validation Rules

1. The `ENV` variable must only contain alphanumeric characters and dots (`.`).
2. The `ENV` variable must not include the file extension (e.g., `.json`).

### Examples

#### Valid Values

- `ENV=prod` results in `abc.prod.json`
- `ENV=dev` results in `abc.dev.json`
- `ENV=staging` results in `abc.staging.json`
```

**Comment by JerryNixon** [comment]
What scenario would ever create this `json.json` part though?

![image](https://github.com/user-attachments/assets/42189bf0-f69b-457b-acef-af356ca22898)

**Comment by abhishekkumams** [comment]
> What scenario would ever create this `json.json` part though?
> 
> ![image](https://private-user-images.githubusercontent.com/1749983/370021704-42189bf0-f69b-457b-acef-af356ca22898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODU0NzYsIm5iZiI6MTcyNzY4NTE3NiwicGF0aCI6Ii8xNzQ5OTgzLzM3MDAyMTcwNC00MjE4OWJmMC1mNjliLTQ1N2ItYWNlZi1hZjM1NmNhMjI4OTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MzBUMDgzMjU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mzg2MDYxOGZmOGE0YWY0Y2I1MDNlZGIzOTBjYjVhOGI0Nzc2NmI2ZmJkYjRkY2UzMTNiNzJhMjRkNWJlNDkxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eC4SZRiNIkkcM7KjIc8738e3SfeZcZXE6SDuUF6ylLU)

if `DAB_ENV = Config/dab-config-bigdog.json` it will lead to the corresponding scenario.
