### ISSUE TITLE
[Bug]: Inconsistent Behavior during Hot Reload for changes in Runtime Section of the config.

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#2392]
### Summary:
When using the Hot Reload feature to update the Runtime section of the configuration, the system does not properly refresh all objects. This leads to inconsistent behavior, specifically resulting in "resource not found" errors after re-enabling REST/GraphQL endpoints.

### Steps to Reproduce:
1. Start the engine and verify that both REST and GraphQL endpoints are accessible.
2. Update the configuration to disable REST/GraphQL in the Runtime section.
3. Observe that the engine reloads and both REST and GraphQL endpoints become inaccessible as expected.
4. Update the configuration again to re-enable REST/GraphQL.
5. Attempt to query the REST and GraphQL endpoints.

### Observed Behavior:
After re-enabling REST/GraphQL, the endpoints are accessible, but querying them results in "resource not found" errors.

### Expected Behavior:
After re-enabling REST/GraphQL, the endpoints should be fully functional and return the expected resources without errors.

### Thoughts:
The issue appears to be related to the incomplete refresh of internal objects during the Hot Reload process. When the configuration is updated to re-enable REST/GraphQL, some objects or states are not properly re-initialized, leading to the "resource not found" errors.

### Possible Root Causes:
**Incomplete State Reset:** Certain internal states or objects are not fully reset or re-initialized during the Hot Reload process.
**Dependency Injection:** Services or dependencies related to REST/GraphQL might not be properly re-injected or re-configured.

### Attachments:

1. REST response (after re-enabling)
![image](https://github.com/user-attachments/assets/d5a32dd1-60fe-48bc-b639-ae6992c4a35d)

2. GraphQL response (after re-enabling)
![image](https://github.com/user-attachments/assets/64bc5842-e553-4765-83a4-ea049eb5e3e3)

### Version

main

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
isn't this due to pending completion of #2324?

**Comment by abhishekkumams** [comment]
> isn't this due to pending completion of #2324?

It shouldn't be because in this case we are not adding or removing any entities. We are just enabling/disabling global endpoints.
