### ISSUE TITLE
[Enhancement]: optimise for point read in config to use Cosmos ReadItemAsync

### ISSUE THREAD

**Issue by golfalot** [Azure/data-api-builder#2399]
### What happened?

With a 2,460 byte document, The cost for a point read is **1.05** RUs, whereas the equivalent `SELECT * FROM c WHERE c.id = '{documentId}'` (where the partition key is /id), the cost is **2.85** RUs

I understand this tool is doing a lot of generic resolving quite brilliantly across multiple data sources, but I and possibly a good many others have datasets in Cosmos which we interrogate using the Cosmos SDK to run cost efficient point reads with ReadItemAsync

I would love an option to specify in my configuration for a given entity that I want the resolver to use ReadItemAsync.
- we'll need a way to specify in config which field names from the schema represent the document id and partition key for ReadItemAsync to use as parameters
- we'll need also need a way to remove fields from the response object which were not requested in the GraphQL query
- I also note this could consume more RUs for very large documents than a comparable SQL api query due to returning unwanted fields

I have a had a look through the source to see how this project hangs together, it's very elegant,  but I very much feel offering a pull request is out of my league.

Thank you considering this enhancement. Tim.

### Version

1.2.11+c7ca8db8558a63919c530e454c8f18b45d5b931c

### What database are you using?

CosmosDB NoSQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by golfalot** [comment]
linking related idea for REST
https://github.com/Azure/data-api-builder/issues/1085

**Comment by golfalot** [comment]
feeling I might have missed a key concept, and this is already a feature of the tool ?
Having defined a singular data source and entity, it surfaces in the schema as two choices
- `item_by_pk`
- `items`

Does this imply `_by_pk` is is indeed using `ReadItemAsync()`. 

I scanned the source code and do indeed find such functionality
https://github.com/Azure/data-api-builder/blob/main/src/Core/Resolvers/CosmosQueryEngine.cs#L290

If true, would be great to surface this in the docs. Sorry if I wasted anybody's time.

**Comment by golfalot** [comment]
Pleased to confirm that `item_by_pk` does indeed use `ReadItemAsync()` when specifying both `id` and `_partitionKeyValue` value conditions in the gql query.

To learn this I ran the source code in debug mode and set a breakpoint.

**Comment by sajeetharan** [comment]
Hey @golfalot Thank you for sharing your feedback! I'm interested in learning more about how you're using DAB. Would you be open to discussing this further?

**Comment by golfalot** [comment]
Hi @sajeetharan. I sent you an email to the address listed on your GitHub profile page. I put my user handle and issue number in the subject line.

**Comment by sajeetharan** [comment]
Hi @golfalot thank you!
