### ISSUE TITLE
[Enhancement] `dab configure --runtime` in CLI

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#2403]
Below are the requirements for adding support for updating runtime section of the config using `dab-configure` command.

| Configuration File Property Path | CLI Flag | Data Type | Nullable |
|-------------------------------------------------------------------------|--------------------------------------------------------------------|-----------|----------|
| runtime.<br/>rest.path | <nobr>--runtime.rest.path</nobr> | String (default: `/api`) | ❌ |
| runtime.<br/>rest.enabled | <nobr>--runtime.rest.enabled</nobr> | Boolean: `true`, `false` (default: `true`) | ❌ |
| runtime.<br/>rest.request-body-strict | <nobr>--runtime.rest.request-body-strict</nobr> | Boolean: `true`, `false` (default: `true`) | ✅ |
| runtime.<br/>graphql.allow-introspection | <nobr>--runtime.graphql.allow-introspection</nobr> | Boolean: `true`, `false` (default: `true`) | ✅ |
| runtime.<br/>graphql.path | <nobr>--runtime.graphql.path</nobr> | String (default: `/graphql`) | ❌ |
| runtime.<br/>graphql.enabled | <nobr>--runtime.graphql.enabled</nobr> | Boolean: `true`, `false` (default: `true`) | ❌ |
| runtime.<br/>graphql.multiple-mutations.create.enabled | <nobr>--runtime.graphql.multiple-mutations.create.enabled</nobr> | Boolean: `true`, `false` (default: `true`) | ✅ |
| runtime.<br/>host.mode | <nobr>--runtime.host.mode</nobr> | String: `Development`, `Production` | ❌ |
| runtime.<br/>host.cors.origins | <nobr>--runtime.host.cors.origins</nobr> | Array of strings | ✅ |
| runtime.<br/>host.cors.allow-credentials | <nobr>--runtime.host.cors.allow-credentials</nobr> | Boolean: `true`, `false` (default: `false`) | ✅ |
| runtime.<br/>host.authentication.provider | <nobr>--runtime.host.authentication.provider</nobr> | String: `StaticWebApps`, `AppService`, `AzureAD`, `Jwt` | ✅ |
| runtime.<br/>host.authentication.jwt.audience | <nobr>--runtime.host.authentication.jwt.audience</nobr> | Array of strings | ✅ |
| runtime.<br/>host.authentication.jwt.issuer | <nobr>--runtime.host.authentication.jwt.issuer</nobr> | String | ✅ |
| runtime.<br/>cache.enabled | <nobr>--runtime.cache.enabled</nobr> | Boolean: `true`, `false` (default: `false`) | ✅ |
| runtime.<br/>cache.ttl-seconds | <nobr>--runtime.cache.ttl-seconds</nobr> | Integer (default: `3600`) | ✅ |

Design guide: Design guide: https://github.com/Azure/data-api-builder/blob/main/docs/design/dab-configure.md

Have a look at the original issue: https://github.com/Azure/data-api-builder/issues/2251
Attached to this issue are other PRs which can be used to get better understanding.

NOTE:
Feel free to break the task into multiple PRs such as rest/graphql/host.

**Comment by abhishekkumams** [comment]
@sezal98, Please don't change the name of this issue. This was created to track dab-configure at a single place. Just like you created the issue for `runtime` and `rest`. once done, you can add those as sub-issue to this task.

![Image](https://github.com/user-attachments/assets/fdf2d077-e906-4d4f-82a4-6ca6fa34e47a)

https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/adding-sub-issues

**Comment by sezal98** [comment]
Added sub issues as suggested.
