### ISSUE TITLE
[Bug]: graphql not working with Jerry walkthrough demo files

### ISSUE THREAD

**Issue by jbennink** [Azure/data-api-builder#2409]
### What happened?

I first installed the global tool. I then downloaded the files from the Github gist, created a local **trek** MSSQLLocalDB database, ran the `startrek.sql` script and then the `startrek.cmd` file. 
Everything ran succesful, but when I `dab start` and go to the `/graphql` endpoint it says "No schema". 
In the demo video Jerry did have a schema out of the box.

Is something missing in the steps not shown in de video or is something not working anymore.

### Version

1.2.11+c7ca8db8558a63919c530e454c8f18b45d5b931c

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

GraphQL

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abhishekkumams** [comment]
@jbennink , can you share the logs please? were you also not able to hit the `rest` endpoints?

**Comment by jbennink** [comment]
I just tried a clean dab-config with just the Actos from the video and in the F12 browser tools I see a 400 error: 
```json
{
    "errors": [
        {
            "message": "The field `isOneOf` does not exist on the type `__Type`.",
            "locations": [
                {
                    "line": 32,
                    "column": 3
                }
            ],
            "path": [
                "__schema",
                "types"
            ],
            "extensions": {
                "type": "__Type",
                "field": "isOneOf",
                "responseName": "isOneOf",
                "specifiedBy": "http://spec.graphql.org/October2021/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types"
            }
        }
    ]
}
```

**Comment by jbennink** [comment]
> @jbennink , can you share the logs please? were you also not able to hit the `rest` endpoints?
the rest endpoint and the swagger both work. As seen in the added comment it seems like a specific errro on the graphql -- javascript -- code?

**Comment by jbennink** [comment]
[abhishekkumams](https://github.com/abhishekkumams)
Like I said, console output is all ok, the UI does not give any errors, except I looked with F12 in the brwoser and got the message shown above.

Looks alomost like an issue with a newerer graphql component?

**Comment by jbennink** [comment]
Went back tot 1.2.10 and 1.1.7 but still the same problem/erro in de F12 tools on a call to /graphql for the `IntrospectionQuery` operation

**Comment by jbennink** [comment]
Hmm, might be released to this issue from 16 hours ago: https://github.com/ChilliCream/graphql-platform/issues/7569

**Comment by abhishekkumams** [comment]
Thanks for the details. we would be monitoring from our side as well.

**Comment by michaelstaib** [comment]
That one is on us. The bug is only happening when switching on the experimental feature of oneOf. We have now integrated oneOf support into BCP so you see it in the schema explorer etc and that caused the issue. There will be a bugfix later today.

**Comment by michaelstaib** [comment]
This one is now fixed and should work again.

**Comment by abhishekkumams** [comment]
@jbennink , Is this issue resolved for you now?

**Comment by seantleonard** [comment]
Please reopen if you are still experiencing issues. Michael has deployed the fix for BCP
