### ISSUE TITLE
Open Telemetry support

### ISSUE THREAD

**Issue by tommasodotNET** [Azure/data-api-builder#2411]
At the moment, DAB only supports Application Insights for telemetry. 

```json
{
  "runtime": {
    ...
    "telemetry": {
      "application-insights": {
        "enabled": true,
        "connection-string": "@env('app-insights-connection-string')"
      }
    },
    ...
  }
}
```

As shown in many demos, DAB integration with Aspire is really easy. It would be nice to have the option to configure DAB to support an open telemetry endpoint as well to improve its integration with Aspire.

The OTEL endpoint and headers are injected by Aspire as environment variables:

endpoint = `OTEL_EXPORTER_OTLP_ENDPOINT`
headers = `OTEL_EXPORTER_OTLP_HEADERS`

Could be something like:

```json
{
  "runtime": {
    ...
    "telemetry": {
      "otel": {
        "enabled": true,
        "endpoint": "@env('OTEL_EXPORTER_OTLP_ENDPOINT')",
        "headers":"@env('OTEL_EXPORTER_OTLP_HEADERS')"
      }
    },
    ...
  }
}
```

**Comment by abhishekkumams** [comment]
Hi @tommasodotNET , thanks for raising the request for supporting OpenTelemetry. 

I wanted to let you know that we already have an existing issue regarding OpenTelemetry support. You can find it here: https://github.com/Azure/data-api-builder/issues/2397

Feel free to add any additional comments or requirements you might have to the existing issue. This will help us consolidate all related discussions and ensure we address everyone's needs effectively.

**Comment by tommasodotNET** [comment]
Sorry about that. I've searched the opened issues before creating this one and didn't find it. We can close this one, I guess...
