### ISSUE TITLE
MySQL: Runtime to Database Authorization

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#242]
Implement a technique to filter out rows based on the claims passed to the runtime to utilize unique capabilities of MySQL. 
For e.g. see this blogpost : https://mariadb.com/resources/blog/protect-your-data-row-level-security-in-mariadb-10-0/

Since in built RLS is not supported, how do we apply the same concepts that we do for Azure SQL DB to MySQL when Hawaii returns results back to the user?

**Comment by Aniruddh25** [comment]
Support for Row level security has been implemented for MsSql see here: https://github.com/Azure/data-api-builder/blob/main/docs/azure-sql-session-context-rls.md This issue is to triage if something similar is possible for MySQL and if so, implement it.

**Comment by howard0su** [comment]
MySQL doesn't support row level security natively. It is doable via some application level implementation as the blog suggested.  But I am not sure if this align with overall direction of DAB?

**Comment by Aniruddh25** [comment]
If there is no native support for RLS, I think we can close this for now since we are not planning application level filtering at the moment.
