### ISSUE TITLE
Add capability to modify the linking table even if it is not exposed to satisfy foreign key constraints

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#285]
In M:N relationships when the linking table is not exposed, we need to make sure mutation on the parent tables trigger deletion of rows in the linking table as well.
E.g. book_author_link should have its row deleted when a book with book_id referenced in that row is deleted from the books table.

**Comment by seantleonard** [comment]
@severussundar @ayush3797 is this needed for Nested mutations?

**Comment by ayush3797** [comment]
> @severussundar @ayush3797 is this needed for Nested mutations?

I don't think this is needed. The user can setup CASCADE DELETE or use an AFTER DELETE trigger to ensure consistency of the linking table. In future, we might consider an option to somehow enable them to specify if they want to peform the deletions in the linking table as well, in which case we can figure out some logic to maintain consistency. However, this for sure should not be an immediate concern.

**Comment by severussundar** [comment]
As outlined in the previous comments, when `CASCADE DELETE`/`CASCADE UPDATE` or triggers are setup, the foreign key integrity is taken care of. 

To support the same via a GraphQL operation through DAB without requiring users to setup triggers or cascade operations, 

1. Update: DAB needs to support nested/multiple update feature where updating a Book + Author is possible.
2. Delete: For delete, the use-case can be the following. Let's say a Book is associated with 3 Authors name Author1, Author2, Author3. The user wants to remove the link between Book and Author3, but not delete Author3 as it can have associations with other Book items. To support this, DAB has to build a net new delete mutation operation where schema defines a way to accept inputs in the linking table; also query generation logic needs to be updated to understand and process such a delete mutation.

**Comment by JerryNixon** [comment]
Current requirement is entities must be in config to be modified. The requirement for table mod is met this way, even if the case of this issue is not. For now, we will keep mod ops limited to entities actually in the config file.
