### ISSUE TITLE
AuthZ Engine: Get User-to-Role Mappings

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#299]
Whether mappings are in:

- Configuration File
- User-to-Role mapping table

Store this data in-memory within the DataGateway runtime.
To start, this step will run during runtime startup.

**Comment by Aniruddh25** [comment]
Closing this as not planned, since we only support 1 Role per request, and expect the request specifies the role to be executed as. User to role mapping needs to be stored in the Client App. FYI @seantleonard.
