### ISSUE TITLE
Pg: Allow the user to specify schema from which to extract data model

### ISSUE THREAD

**Issue by gledis69** [Azure/data-api-builder#349]
`Npgsql` supports a `SearchPath` connection string parameter to specify the starting schema.
This should be useful for users who might have already set up a db under a different schema name than the default `public`.

**Comment by acudworth3** [comment]
@gledis69 or @Aniruddh25 Do either of you have an example of a config file using non public schema? I have this exact need, but cannot seem to figure it out. I'm using the `SearchPath` field in the connection string as mentioned.
