### ISSUE TITLE
Engine Cosmos : Date Type is not supported as part of schema

### ISSUE THREAD

**Issue by sajeetharan** [Azure/data-api-builder#455]
With the current version, engine does not let me to define schema with date type.

type Order @model {
id : ID,
name : String,
customerId : ID,
date : Date,
customerEmail : String,
items : [Inventory]
}

the above schema throws an error

![image](https://user-images.githubusercontent.com/4833351/170729066-775ee716-a804-4162-af15-2b3c7655b73d.png)

**Comment by sourabh1007** [comment]
On startup, there is no more error, `DateTime` is a valid scalar type in graphql
