### ISSUE TITLE
[Known Issue] Azure Cosmos DB Support for Authorization Policies

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#597]
Does this policy support makes sense for Cosmos? If not, should we disable this section for cosmos similar to the[ way we disable the relationship section](https://github.com/Azure/hawaii-engine/blob/4f02b8018a0c4f963bb090e3f06281ca97d3b067/DataGateway.Service/Services/GraphQLSchemaCreator.cs#L187)?

@tarazou9 , @mbhaskar thoughts?

**Comment by tarazou9** [comment]
After discussed with @mbhaskar, Cosmos currently only support entity level authorization, but not field level authorization. 
1. For the "field" section, the included and excluded columns, we could do a pass through, without honoring the setting config and not throwing an exception.
2. For the field auth check in the ```GQLFilterParser```, we will do a skip on the check if it's cosmos, to fix the filter issue that we are seeing right now.

**Comment by tarazou9** [comment]
PR merged for addressing this issue https://github.com/Azure/data-api-builder/pull/1436, going to close this. In the meanwhile, future support for field level auth will need to be planned and designed future.

**Comment by seantleonard** [comment]
Reopening as this is an additional feature beyond entity and field level authZ, as is not yet decided on whether this will be supported in Cosmos

**Comment by sajeetharan** [comment]
@seantleonard We will be adding this support with the next release.  cc : @mbhaskar

**Comment by matthewhampton** [comment]
@sajeetharan I have been trying to understand if I should be expecting something like this:

```
"entities": {
    "User": {
      "source": "users",
      "permissions": [
        {
          "role": "authenticated",
          "actions": [
            {
              "action": "read",
              "policy": {
                "database": "@item.userId eq @claims.userId"
              }
            }
          ]
        }
      ]
    }
  }
```

to filter items based on the userId with Cosmos DB - but it does not seem to.

Does this issue imply that this is not supported yet, or am I just doing something wrong? Will it be in the next release?

Thanks!

@mbhaskar @tarazou9

**Comment by seantleonard** [comment]
@matthewhampton Cosmos doesn't support DAB database policies. Currently, the filter that you referenced will not work. I'll defer to @sajeetharan for whether any timelines are available.

**Comment by sajeetharan** [comment]
Thank you, @matthewhampton. Currently, we do not have an estimated time of arrival (ETA). However, I will follow up with you once we have had a thorough discussion and established a timeline.

**Comment by thomasgauvin** [comment]
+1 @matthewhampton 's ask, this should be included in the functionality for CosmosDB for NoSQL.
