### ISSUE TITLE
Add runtime settings option for rest and graphql to `dab init`

### ISSUE THREAD

**Issue by VinnieKhanna** [Azure/data-api-builder#633]
`host` is configurable with `dab init` through --host-mode and --cors-origin, would be nice to also support changing the default rest and graphql endpoints.

By default:
```json
"runtime": {
    "rest": {
      "enabled": true,
      "path": "/api"
    },
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
```

Would be nice to have: `dab init --rest / --graphql /graphql`
```json
"runtime": {
    "rest": {
      "enabled": true,
      "path": "/"
    },
    "graphql": {
      "allow-introspection": true,
      "enabled": true,
      "path": "/graphql"
    },
```

And of course enabling/disabling each endpoint as well at some point.

**Comment by abhishekkumams** [comment]
completed in https://github.com/Azure/data-api-builder/pull/1229 and https://github.com/Azure/data-api-builder/pull/1309
