### ISSUE TITLE
[CLI]: New command: `dab view`

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#643]
# Proposed Command:
view

# Usage:
To view certain objects (entity,relationship) defined in the runtime config.

# Proposed Commands:
## To view all the entites 
`hawaii view --all-entities`

## To view an entity
`hawaii view <<entity_name>>`

## To view all relationships of an entity
`hawaii view <<entity_name>> --all-relationships`

## To view a particular relationship of an entity
`hawaii view <<entity_name>> --relationship <<relationship_name>>`

**Comment by JerryNixon** [comment]
Great idea we will make it part of the UI.
