### ISSUE TITLE
Auto-import entities/table to configuration file when initializing Hawaii

### ISSUE THREAD

**Issue by thomasgauvin** [Azure/data-api-builder#647]
Currently, a user would have to initialize and import tables manually through the CLI. This adds additional steps for the user, as they have already specified these in their DB. I believe auto importing entities based upon tables when creating the configuration file would make it easier for the user to use. 

Import database objects under a specific Schema (user created databases). This could be done with the most restrictive permissions, simply to help customers scaffold this file.

**Comment by JerryNixon** [comment]
Closing in favor of UI behavior.
