### ISSUE TITLE
GraphQL Schema - ComplexInputType creation for nested object delete mutations

### ISSUE THREAD

**Issue by seantleonard** [Azure/data-api-builder#686]
Currently the code within https://github.com/Azure/data-api-builder/blob/5993e8480836411b8abaa31fca10b88a2fea1dfc/src/Service.GraphQLBuilder/Mutations/DeleteMutationBuilder.cs
does not create complex input type objects which are used to facilitate nested GraphQL object operations.

At this time, the intent is that Cosmos would support it, and then SQL databases in the future.

**Comment by JerryNixon** [comment]
Closing until customer demand.
