### ISSUE TITLE
Should we do union of configuration properties specified in `dab-config.json` and `dab-config.<Environment>.json`?

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#714]
Currently, the configuration properties are NOT additive. So, for example, a property is defined in dab-config.json, but NOT defined in dab-config.Development.json, it will be considered undefined since we give preference to the environment specific file.

This issue is to discuss if such a union is desirable? What to do when missing properties are conflicting with each other?

See this discussion: https://github.com/Azure/data-api-builder/pull/678/files#r947322896

**Comment by abhishekkumams** [comment]
similar to #722

**Comment by Aniruddh25** [comment]
Duplicate
