### ISSUE TITLE
Automatic reload of configuration file when running on-prem

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#892]
Would be great to have a switch on the CLI, something like `--watch` that will automatically reload the configuration file (and thus re-generate the in-memory schema) whenever the file is changed. Something like https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-watch

That would greatly improve development velocity.

**Comment by aaronburtle** [comment]
Duplicate issue with #67 https://github.com/Azure/data-api-builder/issues/67
