### ISSUE TITLE
Add support for CosmosDB PostgreSQL

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#958]
Creating this issue to track what kind of support we would want `dab` to provide for CosmosDb for PostgreSQL and the related testing

**Comment by Aniruddh25** [comment]
@GaryHopeMS #1078 was closed as a duplicate of this one. The support for `cosmosdb_postgresql` variant in DAB is still required and lets track it in this issue.

**Comment by mmwaikar** [comment]
I am also looking forward to CosmosDB for PostgreSQL support in DAB.

**Comment by sajeetharan** [comment]
Closing this as it's not planned anytime soon.
