### ISSUE TITLE
Additional Authentication Providers

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#966]
# Summary
Increase the number of Authentication providers supported 

# Motivation
Right now, only EasyAuth and Azure AD are supported. Common authentication providers like Auth0 and in general support for any provider compatible with the OAuth2 protocol should be provided. This would eneable also on-prem users to use custom or third party OAuth2 providers they trust.

# Functional Specifications
Using the `jwt` section in the configuration file it will be possible to specify, like already implemented,

- `issuer` that will be used to validate the token received
- `audience` that will be used to determine the used/required scope

there will be also the ability to specify where the role claims can be found using a dedicated option

- `roles.path` will allow to specify JSON path where roles are in the received JWT token.

For example, for an Azure AD token the `roles.path` would be `roles`

# Prior Work
A discuss arone the topic was started in [#719](https://github.com/Azure/data-api-builder/issues/719)

**Comment by JerryNixon** [comment]
Closing in favor of other issues that are more specific to enable use cases.
