### ISSUE TITLE
DAB CLI : Windows Installer Support

### ISSUE THREAD

**Issue by sajeetharan** [Azure/data-api-builder#999]
There is a feedback from a customer to have .msi installer for the DAB CLI. Right now if the customer uses the exe version, there is no way to execute the exe and use it directly.

For users who are not familiar with .Net Nuget packages they would be expecting it to use the installer.

**Comment by abhishekkumams** [comment]
As part of release package, we also publish the dab package windows/macOS/linux platform. For windows user, if they want to use the exe, they can directly download the [zip](https://github.com/Azure/data-api-builder/releases/download/v0.5.34/dab_win-x64-0.5.34.zip) which is present in the [release page](https://github.com/Azure/data-api-builder/releases) and extract the zip and directly use the exe.

They'll have the same experience.

Once they have unpacked the zip. Below comands would work perfectly

`Microsoft.DataApiBuilder.exe init --database-type mssql`
`Microsoft.DataApiBuilder.exe start`

NOTE: dotnet is not required when using the executable directly.

**Comment by sajeetharan** [comment]
Thanks @abhishekkumams looks good.
